"use client";

/**
 * Administration, migrated.
 *
 * The vanilla admin area is four screens deep: an editorial workspace where
 * sources are uploaded in chunks, accepted for rights, extracted, mapped,
 * generated by a model, reviewed artifact by artifact and finally published as
 * a versioned release; a per-course workbench; a programme curriculum editor;
 * and an academic-calendar intake. Every one of those is a write path over
 * material students will be taught from. The React surface keeps orchestration
 * here while the safety gates and payload rules live in lib/app modules tested
 * directly by node:test.
 */

import { useEffect, useMemo, useState } from "react";
import { ChevronRightIcon } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import {
  Empty,
  EmptyDescription,
  EmptyHeader,
  EmptyTitle,
} from "@/components/ui/empty";
import { Progress } from "@/components/ui/progress";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useJson } from "@/components/workspace/use-json";
import { AdminIntake } from "@/components/workspace/admin-intake";
import { AdminProduction } from "@/components/workspace/admin-production";
import { AdminCatalogue } from "@/components/workspace/admin-catalogue";
import { formatBytes, formatCount } from "@/lib/workspace/account.mjs";
import {
  type AdminCourse,
  type AdminStatus,
  type ContentRequest,
  type Coverage,
  type Edition,
  type IngestionStage,
  REQUEST_STATUS_LABEL,
  attentionQueue,
  coverageRows,
  editionStage,
  openRequests,
  releaseCounters,
} from "@/lib/workspace/admin.mjs";

const NUMERALS = "font-data tabular-nums";
const RULE =
  "text-muted-foreground text-[10.5px] font-semibold tracking-[0.11em] uppercase";

function relative(value: string | null | undefined) {
  if (!value) return null;
  const diff = Date.now() - new Date(value).getTime();
  if (Number.isNaN(diff)) return null;
  if (diff < 0) return "just now";
  const minutes = Math.round(diff / 60_000);
  if (minutes < 1) return "just now";
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.round(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  return `${Math.round(hours / 24)}d ago`;
}

function Section({
  title,
  note,
  action,
  children,
}: {
  title: string;
  note?: React.ReactNode;
  action?: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <section className="flex flex-col gap-3">
      <div className="flex items-baseline justify-between gap-6 border-b pb-2">
        <div className="flex flex-col gap-0.5">
          <h2 className="text-sm font-semibold">{title}</h2>
          {note && <p className="text-muted-foreground text-sm">{note}</p>}
        </div>
        {action}
      </div>
      {children}
    </section>
  );
}

function Failed({ what, message }: { what: string; message: string }) {
  return (
    <Alert>
      <AlertTitle>{what}</AlertTitle>
      <AlertDescription>{message}</AlertDescription>
    </Alert>
  );
}

// ----- Overview -----------------------------------------------------------

function Overview({
  status,
  statusError,
  editions,
  editionsError,
  requests,
  requestsError,
}: {
  status: AdminStatus | null;
  statusError: string | null;
  editions: Edition[] | null;
  editionsError: string | null;
  requests: ContentRequest[] | null;
  requestsError: string | null;
}) {
  const queue = useMemo(
    () =>
      attentionQueue({ editions: editions ?? [], requests: requests ?? [] }),
    [editions, requests],
  );
  const counters = releaseCounters(status);
  // An empty queue only means "nothing waiting" when both sources were read.
  const unread = [
    editionsError ? "editions" : null,
    requestsError ? "course requests" : null,
  ].filter(Boolean);

  return (
    <div className="flex flex-col gap-8">
      <Section
        title="Needs attention"
        note="Every edition and request waiting on a decision, most urgent first."
        action={
          queue.length ? (
            <span className={`text-muted-foreground text-sm ${NUMERALS}`}>
              {queue.length} open
            </span>
          ) : null
        }
      >
        {unread.length > 0 && (
          <Failed
            what={`This queue is incomplete — ${unread.join(" and ")} could not be read`}
            message={[editionsError, requestsError].filter(Boolean).join(" ")}
          />
        )}
        {!editions && !requests && !unread.length ? (
          <Skeleton className="h-24 w-full" />
        ) : queue.length ? (
          <ul className="flex flex-col">
            {queue.map((item) => (
              <li key={item.id}>
                <a
                  href={item.href}
                  className="hover:bg-card grid grid-cols-[minmax(0,1fr)_auto] items-center gap-4 border-b py-2.5"
                >
                  <span className="flex min-w-0 flex-col gap-0.5">
                    <strong className="text-[15px] font-medium">
                      {item.title}
                    </strong>
                    <small className="text-muted-foreground text-xs">
                      {item.detail}
                    </small>
                  </span>
                  <ChevronRightIcon className="text-muted-foreground size-4" />
                </a>
              </li>
            ))}
          </ul>
        ) : unread.length ? null : (
          <Empty>
            <EmptyHeader>
              <EmptyTitle>Nothing is waiting</EmptyTitle>
              <EmptyDescription>
                {editions?.length
                  ? "Every edition is published"
                  : "No course is in production yet"}{" "}
                and the intake inbox is clear.
              </EmptyDescription>
            </EmptyHeader>
          </Empty>
        )}
      </Section>

      <Section
        title="Published content"
        note="Everything students currently see, across every programme."
        action={
          status?.writable && status.releaseId != null ? (
            <span className={`text-muted-foreground text-sm ${NUMERALS}`}>
              Release {status.releaseId}
              {status.activatedAt
                ? ` · activated ${relative(status.activatedAt)}`
                : ""}
            </span>
          ) : null
        }
      >
        {statusError ? (
          <Failed
            what="The active release could not be read"
            message={statusError}
          />
        ) : !status ? (
          <Skeleton className="h-16 w-full" />
        ) : !status.writable ? (
          <p className="text-muted-foreground text-sm">
            This server reads content from repository files, so there is no
            release to count and editorial writes are unavailable. Both need the
            hosted database.
          </p>
        ) : (
          <dl className="flex flex-wrap gap-x-12 gap-y-6">
            {counters.map((counter) => (
              <div
                key={counter.key}
                className="flex min-w-[6rem] flex-col gap-1"
              >
                <dt className={RULE}>{counter.label}</dt>
                <dd
                  className={`text-2xl font-semibold tracking-tight ${NUMERALS}`}
                >
                  {counter.value === null ? "—" : formatCount(counter.value)}
                </dd>
              </div>
            ))}
          </dl>
        )}
      </Section>

      <Section
        title="Editions in production"
        note="Every edition the editorial workspace is tracking, newest first."
      >
        {editionsError ? (
          <Failed
            what="The editorial workspace could not be read"
            message={editionsError}
          />
        ) : !editions ? (
          <Skeleton className="h-24 w-full" />
        ) : !editions.length ? (
          <Empty>
            <EmptyHeader>
              <EmptyTitle>No editions yet</EmptyTitle>
              <EmptyDescription>
                An edition is created when a course enters the source-grounded
                pipeline.
              </EmptyDescription>
            </EmptyHeader>
          </Empty>
        ) : (
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Course</TableHead>
                <TableHead>Year</TableHead>
                <TableHead>Stage</TableHead>
                <TableHead>Next</TableHead>
                <TableHead className="text-right">Updated</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {editions.map((edition) => {
                const stage = editionStage(edition);
                return (
                  <TableRow key={edition.id}>
                    <TableCell>
                      <span className="flex flex-col gap-0.5">
                        <strong
                          className={`text-[15px] font-semibold ${NUMERALS}`}
                        >
                          {edition.courseCode || "—"}
                        </strong>
                        <small className="text-muted-foreground text-xs">
                          {edition.courseName}
                        </small>
                      </span>
                    </TableCell>
                    <TableCell className={`text-muted-foreground ${NUMERALS}`}>
                      {[edition.academicYear, edition.period]
                        .filter(Boolean)
                        .join(" · ") || "—"}
                    </TableCell>
                    <TableCell>
                      {/* State is a mark: only what still needs a decision is emphasised. */}
                      {stage.next ? (
                        <Badge variant="secondary">{stage.label}</Badge>
                      ) : (
                        <span className="text-muted-foreground text-sm">
                          {stage.label}
                        </span>
                      )}
                    </TableCell>
                    <TableCell className="text-muted-foreground text-sm">
                      {stage.next ?? "Nothing outstanding"}
                    </TableCell>
                    <TableCell
                      className={`text-muted-foreground text-right ${NUMERALS}`}
                    >
                      {relative(edition.updatedAt) ?? "—"}
                    </TableCell>
                  </TableRow>
                );
              })}
            </TableBody>
          </Table>
        )}
      </Section>
    </div>
  );
}

// ----- Course intake ------------------------------------------------------

function Intake({
  requests,
  requestsError,
  stages,
  categories,
}: {
  requests: ContentRequest[] | null;
  requestsError: string | null;
  stages: IngestionStage[];
  categories: [string, string][];
}) {
  const open = openRequests(requests);
  const stageLabel = new Map(stages.map((stage) => [stage.id, stage.label]));
  const categoryLabel = new Map(categories);

  return (
    <div className="flex flex-col gap-8">
      <Section
        title="Course intake inbox"
        note="Student evidence enters the standard source-grounded pipeline. Nothing becomes public until rights, coverage, citations, exercises and quality have been reviewed."
        action={
          requests?.length ? (
            <span className={`text-muted-foreground text-sm ${NUMERALS}`}>
              {open.length} open of {requests.length}
            </span>
          ) : null
        }
      >
        {requestsError ? (
          <Failed
            what="Course requests could not be read"
            message={requestsError}
          />
        ) : !requests ? (
          <Skeleton className="h-32 w-full" />
        ) : !requests.length ? (
          <Empty>
            <EmptyHeader>
              <EmptyTitle>No course requests yet</EmptyTitle>
              <EmptyDescription>
                Courses without maintained content send their material here.
              </EmptyDescription>
            </EmptyHeader>
          </Empty>
        ) : (
          <ul className="flex flex-col">
            {requests.map((request) => (
              <li
                key={request.id}
                className="flex flex-col gap-2 border-b py-3"
              >
                <div className="flex items-baseline justify-between gap-6">
                  <span className="flex min-w-0 flex-col gap-0.5">
                    <strong className="text-[15px] font-medium">
                      <span className={NUMERALS}>
                        {request.courseCode || "Course"}
                      </span>{" "}
                      · {request.courseName}
                    </strong>
                    <small
                      className={`text-muted-foreground text-xs ${NUMERALS}`}
                    >
                      {[request.period, request.academicYear]
                        .filter(Boolean)
                        .join(" · ") || "Academic context not supplied"}
                      {" · "}
                      {request.files.length} file
                      {request.files.length === 1 ? "" : "s"}
                      {" · "}
                      {request.contributionConsent
                        ? `shared candidate (${request.contributionLicense || "basis not recorded"})`
                        : "private request"}
                    </small>
                  </span>
                  <span className="flex items-center gap-3 whitespace-nowrap">
                    <small className="text-muted-foreground text-xs">
                      {stageLabel.get(request.pipelineStage) ??
                        request.pipelineStage}
                    </small>
                    {request.status === "submitted" ||
                    request.status === "review" ? (
                      <Badge>
                        {REQUEST_STATUS_LABEL[request.status] ?? request.status}
                      </Badge>
                    ) : (
                      <span className="text-muted-foreground text-sm">
                        {REQUEST_STATUS_LABEL[request.status] ?? request.status}
                      </span>
                    )}
                  </span>
                </div>
                <div
                  className={`text-muted-foreground flex flex-wrap gap-x-6 gap-y-1 text-xs ${NUMERALS}`}
                >
                  <span>
                    From{" "}
                    {request.requesterEmail ||
                      request.userId ||
                      "unknown account"}
                  </span>
                  <span>Sent {relative(request.createdAt) ?? "—"}</span>
                  {request.categories.length > 0 && (
                    <span>
                      {request.categories
                        .map(
                          (category) => categoryLabel.get(category) ?? category,
                        )
                        .join(", ")}
                    </span>
                  )}
                </div>
                {request.notes && (
                  <p className="text-muted-foreground max-w-[80ch] text-sm whitespace-pre-line">
                    {request.notes}
                  </p>
                )}
                {request.files.length > 0 && (
                  <ul
                    className={`text-muted-foreground flex flex-wrap gap-x-4 gap-y-1 text-xs ${NUMERALS}`}
                  >
                    {request.files.map((file) => (
                      <li key={file.id}>
                        {/* The download route is authenticated and private; it is a link, not an embed. */}
                        <a
                          className="text-primary font-semibold"
                          href={`/api/admin/content-requests/${encodeURIComponent(request.id)}/files/${encodeURIComponent(file.id)}`}
                        >
                          {file.name}
                        </a>{" "}
                        {formatBytes(file.size)}
                      </li>
                    ))}
                  </ul>
                )}
                {request.urls.length > 0 && (
                  <ul className="flex flex-col gap-1 text-xs">
                    {request.urls.map((url) => (
                      <li key={url}>
                        <a
                          className="text-primary font-semibold break-all"
                          href={url}
                          target="_blank"
                          rel="noopener noreferrer"
                        >
                          {url}
                        </a>
                      </li>
                    ))}
                  </ul>
                )}
                {request.adminNote && (
                  <p className="text-muted-foreground max-w-[80ch] border-l pl-3 text-sm">
                    Internal note: {request.adminNote}
                  </p>
                )}
              </li>
            ))}
          </ul>
        )}
      </Section>
    </div>
  );
}

// ----- Coverage -----------------------------------------------------------

function CoverageTab() {
  const coverage = useJson<Coverage>("/api/coverage");
  const courses = useJson<{ courses: AdminCourse[] }>("/api/courses");
  const rows = useMemo(
    () => coverageRows(coverage.data, courses.data?.courses ?? []),
    [coverage.data, courses.data],
  );

  return (
    <div className="flex flex-col gap-8">
      <Section
        title="Generation coverage"
        note="How much of each active course's prepared material exists, counted in the same steps the content pipeline plans."
        action={
          coverage.data ? (
            <span className={`text-muted-foreground text-sm ${NUMERALS}`}>
              {coverage.data.totalPending} of {coverage.data.totalSteps} steps
              pending
            </span>
          ) : null
        }
      >
        {coverage.error ? (
          <Failed what="Coverage could not be read" message={coverage.error} />
        ) : !coverage.data ? (
          <Skeleton className="h-32 w-full" />
        ) : !rows.length ? (
          <Empty>
            <EmptyHeader>
              <EmptyTitle>No active courses</EmptyTitle>
              <EmptyDescription>
                Coverage is counted over courses that are not archived.
              </EmptyDescription>
            </EmptyHeader>
          </Empty>
        ) : (
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Course</TableHead>
                <TableHead className="text-right">Done</TableHead>
                <TableHead className="text-right">Pending</TableHead>
                <TableHead className="w-[14rem]">Coverage</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {rows.map((row) => (
                <TableRow key={row.id}>
                  <TableCell>
                    <span className="flex flex-col gap-0.5">
                      <strong
                        className={`text-[15px] font-semibold ${NUMERALS}`}
                      >
                        {row.code}
                      </strong>
                      <small className="text-muted-foreground text-xs">
                        {row.name}
                      </small>
                    </span>
                  </TableCell>
                  <TableCell className={`text-right ${NUMERALS}`}>
                    {row.done}
                  </TableCell>
                  <TableCell className={`text-right ${NUMERALS}`}>
                    {row.pending || "—"}
                  </TableCell>
                  <TableCell>
                    {/* A course with no planned steps has unknown coverage, not full coverage. */}
                    {row.percent === null ? (
                      <span className="text-muted-foreground text-sm">
                        No steps planned
                      </span>
                    ) : (
                      <span className="flex items-center gap-3">
                        <Progress value={row.percent} />
                        <small
                          className={`text-muted-foreground text-xs ${NUMERALS}`}
                        >
                          {row.percent}%
                        </small>
                      </span>
                    )}
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        )}
        <p className="text-muted-foreground max-w-[80ch] text-sm">
          Generation is not started from here, and no longer can be from
          anywhere in the app: the server refuses
          <code className="text-xs"> POST /api/generate-all-courses</code> as
          managed content, whoever asks. Prepared material is produced by the
          content pipeline in the repository and published as an editorial
          release.
        </p>
      </Section>
    </div>
  );
}

// ----- the page -----------------------------------------------------------

const TABS = [
  ["overview", "Overview"],
  ["intake", "Course intake"],
  ["coverage", "Coverage"],
  ["production", "Production"],
  ["catalogue", "Programmes & calendar"],
] as const;

export default function AdminPage() {
  const me = useJson<{ admin: boolean; userId: string; mode: string }>(
    "/api/me",
  );
  const admin = me.data?.admin === true;
  const status = useJson<AdminStatus>(admin ? "/api/admin/status" : null);
  const requests = useJson<{
    requests: ContentRequest[];
    stages: IngestionStage[];
    categories: [string, string][];
  }>(admin ? "/api/admin/content-requests" : null);
  // The editorial workspace is a database-only table set; on a file-backed
  // server the route answers with an error, so it is not asked at all.
  const editions = useJson<{ editions: Edition[] }>(
    admin && status.data?.writable ? "/api/admin/editorial-workspace" : null,
  );
  const catalogue = useJson<{
    programmes: {
      id: string;
      name: string;
      degree?: string;
      versions: any[];
      calendar?: any[];
    }[];
  }>(admin ? "/api/editorial-programmes" : null);
  const [tab, setTab] = useState<string>("overview");
  useEffect(() => {
    const requested = new URLSearchParams(window.location.search).get("tab");
    if (requested && TABS.some(([id]) => id === requested)) setTab(requested);
  }, []);

  if (me.error) {
    return (
      <div className="mx-auto w-full max-w-[1180px] p-5 sm:p-8">
        <Empty>
          <EmptyHeader>
            <EmptyTitle>Your access could not be checked</EmptyTitle>
            <EmptyDescription>{me.error}</EmptyDescription>
          </EmptyHeader>
        </Empty>
      </div>
    );
  }

  if (!me.data) {
    return (
      <div
        className="mx-auto flex w-full max-w-[1180px] flex-col gap-3 p-5 sm:p-8"
        aria-busy="true"
      >
        <Skeleton className="h-12 w-80" />
        <Skeleton className="h-4 w-64" />
      </div>
    );
  }

  if (!admin) {
    return (
      <div className="mx-auto w-full max-w-[1180px] p-5 sm:p-8">
        <Empty>
          <EmptyHeader>
            <EmptyTitle>
              Administration is not available to this account
            </EmptyTitle>
            <EmptyDescription>
              This area is limited to Wicker Study administrators. Everything
              you can do is in your own workspace.
            </EmptyDescription>
          </EmptyHeader>
          <a href="/app" className="text-primary text-sm font-semibold">
            Back to the workspace
          </a>
        </Empty>
      </div>
    );
  }

  const openCount = openRequests(requests.data?.requests ?? []).length;

  return (
    <div className="mx-auto flex w-full max-w-[1180px] flex-col gap-6 p-5 sm:p-8">
      <header className="flex flex-col gap-1">
        <h1 className="font-heading text-[32px] leading-[1.1] font-semibold tracking-[-0.03em]">
          Editorial workspace
        </h1>
        <p className={`text-muted-foreground text-sm ${NUMERALS}`}>
          {status.error
            ? status.error
            : !status.data
              ? "Reading the active release…"
              : status.data.writable
                ? `Active release ${status.data.releaseId}${status.data.activatedAt ? ` · activated ${relative(status.data.activatedAt)}` : ""} · changes take effect immediately`
                : "Content is served from repository files on this server, so editorial writes are unavailable."}
        </p>
      </header>

      <Tabs
        value={tab}
        onValueChange={(value) => {
          const next = String(value);
          setTab(next);
          history.replaceState(null, "", `/app/admin?tab=${next}`);
        }}
        className="gap-6"
      >
        <TabsList>
          {TABS.map(([id, label]) => (
            <TabsTrigger key={id} value={id} className="gap-1.5">
              {label}
              {id === "intake" && openCount > 0 && (
                <span className={`text-muted-foreground ${NUMERALS}`}>
                  {openCount}
                </span>
              )}
            </TabsTrigger>
          ))}
        </TabsList>

        <TabsContent value="overview">
          {tab === "overview" && (
            <Overview
              status={status.data}
              statusError={status.error}
              editions={
                status.data?.writable ? (editions.data?.editions ?? null) : []
              }
              editionsError={editions.error}
              requests={requests.data?.requests ?? null}
              requestsError={requests.error}
            />
          )}
        </TabsContent>

        <TabsContent value="intake">
          {tab === "intake" &&
            (requests.error ? (
              <Failed
                what="The intake inbox could not be read"
                message={requests.error}
              />
            ) : requests.data ? (
              <AdminIntake
                initialRequests={requests.data.requests ?? []}
                stages={requests.data?.stages ?? []}
                onPrepared={() => {
                  editions.reload();
                  requests.reload();
                }}
              />
            ) : (
              <Skeleton className="h-48 w-full" />
            ))}
        </TabsContent>

        <TabsContent value="coverage">
          {tab === "coverage" && <CoverageTab />}
        </TabsContent>

        <TabsContent value="production">
          {tab === "production" && <AdminProduction />}
        </TabsContent>

        <TabsContent value="catalogue">
          {tab === "catalogue" &&
            (catalogue.error ? (
              <Failed
                what="The maintained programme catalogue could not be read"
                message={catalogue.error}
              />
            ) : catalogue.data ? (
              <AdminCatalogue
                initialProgrammes={catalogue.data.programmes ?? []}
              />
            ) : (
              <Skeleton className="h-64 w-full" />
            ))}
        </TabsContent>
      </Tabs>
    </div>
  );
}
