"use client";

import { type ReactNode, useState } from "react";
import Link from "next/link";
import { CheckIcon, CopyIcon, ExternalLinkIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

type Client = "codex" | "claude";
const SECTIONS = [
  ["remote-mcp", "Hosted connection"],
  ["quickstart", "Quickstart"], ["connect", "Connect an agent"], ["update", "Updates & migration"], ["local-generation", "Local generation"], ["capabilities", "What it can do"],
  ["tools", "Tool reference"], ["two-way", "Save context & attendance"], ["canvas-refresh", "Canvas refresh"], ["feedback", "Feedback"], ["activity", "AI activity"], ["context", "How context works"], ["files", "Files and retrieval"],
  ["permissions", "Permissions"], ["tokens", "Tokens and revocation"], ["troubleshooting", "Troubleshooting"], ["http", "HTTP API"],
] as const;

function connectionCommand(client: Client, origin: string, migrate = false) {
  const remove = client === "codex" ? "codex mcp remove wicker-study" : "claude mcp remove --scope user wicker-study";
  const connect = client === "codex"
    ? `codex mcp add wicker-study --url ${origin}/api/mcp\ncodex mcp login wicker-study --scopes read,write`
    : `claude mcp add --scope user --transport http wicker-study ${origin}/api/mcp`;
  return migrate ? `${remove}\n${connect}` : connect;
}

function ConnectionCommands({ origin, migrate = false }: { origin: string; migrate?: boolean }) {
  return <Tabs defaultValue="codex" className="gap-0 border">
    <TabsList variant="line" className="h-12 justify-start px-5"><TabsTrigger value="codex">Codex</TabsTrigger><TabsTrigger value="claude">Claude Code</TabsTrigger></TabsList>
    {(["codex", "claude"] as const).map(client => <TabsContent key={client} value={client} className="mt-0">
      <CommandBlock command={connectionCommand(client, origin, migrate)} />
      <p className="border-t px-5 py-4 text-sm leading-relaxed text-muted-foreground">{client === "codex" ? "Complete the browser sign-in and approve the displayed permissions. Restart your Codex session, reopen the app, or reload the IDE extension window to load the connection." : "Open Claude Code and run /mcp. Select wicker-study and authenticate, then approve the displayed permissions in your browser. Restart an already-open session if the server is missing."}</p>
    </TabsContent>)}
  </Tabs>;
}

function CommandBlock({ command, label = "Run these commands in your terminal" }: { command: string; label?: string }) {
  const [copied, setCopied] = useState(false);
  return <div><div className="flex items-center justify-between gap-4 border-b px-4 py-2.5 sm:px-5"><span className="text-muted-foreground text-xs">{label}</span><Button variant="ghost" size="sm" onClick={async () => { await navigator.clipboard.writeText(command); setCopied(true); }}>{copied ? <CheckIcon data-icon="inline-start" /> : <CopyIcon data-icon="inline-start" />}{copied ? "Copied" : "Copy block"}</Button></div><pre className="bg-muted/25 overflow-x-auto px-4 py-4 text-xs leading-6 sm:px-5"><code>{command}</code></pre></div>;
}

function DocSection({ id, title, intro, children }: { id: string; title: string; intro?: string; children: ReactNode }) {
  return <section id={id} className="scroll-mt-8 border-t pt-8 first:border-t-0 first:pt-0"><h2 className="font-heading text-[26px] leading-tight font-semibold tracking-[-0.025em]">{title}</h2>{intro && <p className="text-muted-foreground mt-2 max-w-[72ch] text-[15px] leading-7">{intro}</p>}<div className="mt-5">{children}</div></section>;
}

function ToolGroup({ title, detail, tools }: { title: string; detail: string; tools: string[] }) {
  return <div className="grid gap-3 border-t py-4 first:border-t-0 sm:grid-cols-[10rem_minmax(0,1fr)]"><div><h3 className="text-sm font-semibold">{title}</h3><p className="text-muted-foreground mt-1 text-xs leading-relaxed">{detail}</p></div><div className="flex flex-wrap content-start gap-1.5">{tools.map((tool) => <code key={tool} className="bg-muted rounded px-2 py-1 text-xs">{tool}</code>)}</div></div>;
}

export default function WorkspaceDocsPage() {
  const origin = typeof window === "undefined" ? "https://study.wicker.life" : window.location.origin;

  return <div className="mx-auto w-full max-w-[1320px] px-4 py-6 sm:px-6 sm:py-8 lg:px-8">
    <header className="grid gap-5 border-b pb-7 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-end"><div><span className="text-muted-foreground text-[10.5px] font-semibold tracking-[0.12em] uppercase">Documentation</span><h1 className="font-heading mt-2 text-[36px] leading-none font-semibold tracking-[-0.035em]">Connect your study workspace</h1><p className="text-muted-foreground mt-3 max-w-[68ch] text-[15px] leading-6">Connect Codex, Claude or another MCP client over HTTPS to work with the same courses, private documents, calendar and saved plan you see here.</p></div><div className="flex gap-2"><Button variant="outline" nativeButton={false} render={<Link href="/connect/remote" />}>Manage connections</Button><Button variant="ghost" nativeButton={false} render={<a href="/api/agent/manifest" target="_blank" rel="noreferrer" />}>API manifest<ExternalLinkIcon data-icon="inline-end" /></Button></div></header>
    <div className="grid items-start gap-10 py-8 lg:grid-cols-[14rem_minmax(0,1fr)] lg:gap-14">
      <aside className="sticky top-6 hidden lg:block"><p className="text-muted-foreground mb-3 text-[10.5px] font-semibold tracking-[0.12em] uppercase">On this page</p><nav aria-label="Documentation sections" className="border-l">{SECTIONS.map(([id, label]) => <a key={id} href={`#${id}`} className="text-muted-foreground hover:text-foreground hover:border-foreground -ml-px block border-l border-transparent px-4 py-2 text-sm">{label}</a>)}</nav></aside>
      <article className="flex min-w-0 max-w-[900px] flex-col gap-12">
        <DocSection id="remote-mcp" title="Connect over HTTPS" intro="Use the hosted MCP for local agents and other services. No Wicker package, Node.js installation or separate skill download is needed.">
          <p className="mb-3">Server URL: <code>{origin}/api/mcp</code> · Transport: Streamable HTTP over HTTPS.</p>
          <p className="mb-3">Choose OAuth in your client, sign in to Wicker Study, and approve the service and permissions shown. Your agent manages the connection credentials. Connect Canvas separately in Wicker Study settings; agents never need your Canvas token.</p>
          <p className="mb-3">Clients that support Bearer API keys can use a scoped key from <Link className="text-primary underline" href="/app/settings?tab=api">Settings → API access</Link>. Configure it in the client’s credential settings, never in a chat or URL.</p>
          <p className="text-sm text-muted-foreground">Request and token budgets apply per account and connection. A 429 response includes <code>Retry-After</code>. External agents’ own model usage is billed by their provider.</p>
        </DocSection>
        <DocSection id="quickstart" title="Quickstart" intro="Connect once, approve access in your browser, then use your existing agent."><ol className="grid border sm:grid-cols-3">{[["01", "Add the server", "Use the Codex or Claude Code command below, or enter the HTTPS URL in your client."], ["02", "Approve access", "Sign in to Wicker Study and review the permissions. No API key needs to be copied."], ["03", "Check the connection", "Ask the agent to call wicker_status, wicker_guidance, then list_courses."]].map(([n, title, copy], index) => <li key={n} className={`p-5 ${index ? "border-t sm:border-t-0 sm:border-l" : ""}`}><span className="font-data text-primary text-xs font-semibold">{n}</span><strong className="mt-3 block text-sm">{title}</strong><p className="text-muted-foreground mt-1 text-xs leading-relaxed">{copy}</p></li>)}</ol></DocSection>
        <DocSection id="connect" title="Connect your agent" intro="These commands add a new hosted connection. If wicker-study is already registered, use the migration commands below.">
          <ConnectionCommands origin={origin} />
          <p className="mt-4 text-sm"><a className="text-primary underline" href="#update">Already using the npm package? Switch your existing connection.</a></p>
          <p className="mt-3 text-sm text-muted-foreground">For other clients, add a remote MCP server with the URL above and choose OAuth. The client must support Streamable HTTP and OAuth dynamic client registration with PKCE, or accept a scoped Bearer API key.</p>
          <p className="mt-3 text-sm text-muted-foreground">Client documentation: <a className="text-primary underline" href="https://developers.openai.com/codex/mcp" target="_blank" rel="noreferrer">Codex MCP configuration</a> · <a className="text-primary underline" href="https://code.claude.com/docs/en/mcp" target="_blank" rel="noreferrer">Claude Code MCP configuration</a>.</p>
        </DocSection>
        <DocSection id="update" title="Updates and switching from the package" intro="Hosted tools and workflow guidance update on the server. Reconnect or restart your agent to refresh tool discovery, then call wicker_status and wicker_guidance. There is no npm or separate skill update for hosted connections.">
          <p className="mb-4 text-sm leading-relaxed">To replace an existing standard package registration, run the commands for your client below and approve the new OAuth connection. They change the agent’s configuration, not your Wicker Study account or saved study data.</p>
          <ConnectionCommands origin={origin} migrate />
          <p className="mt-4 text-sm text-muted-foreground">Claude commands use user scope. If your existing entry uses project or local scope, use that same scope when removing and adding it. Preserve custom settings you still need, and check project overrides if an older connection keeps loading.</p>
          <p className="mt-3 text-sm text-muted-foreground">The old helper’s saved key is not used by OAuth and is not automatically revoked. If nothing else uses it, revoke it in <Link className="text-primary underline" href="/app/settings?tab=api">API access</Link>. An optional installed skill is only a discovery hint; the current guide comes from MCP.</p>
        </DocSection>
        <DocSection id="capabilities" title="What the connection can do" intro="The MCP exposes the workspace as small, explicit tools. Reads are source-grounded; every write requires its own explicit confirmation in your conversation with the agent."><div className="overflow-hidden rounded-xl border">{[["Course work", "Search maintained and private course material, read chapters, questions, flashcards, mistakes and mocks."], ["Programme rules", "Retrieve the governing EER and Board of Examiners rules by academic year with exact page citations."], ["Study situation", "Read deadlines, announcements, timetable blocks, attendance, progress and academic dates."], ["Planning", "Inspect exam sittings and electives, then update the saved plan through revision-checked operations."], ["Practice", "Submit answers, review cards, record chapter reading and maintain the student’s private practice state."], ["Canvas", "Read full assignment briefs and feedback, search announcements and indexed sources, and inspect or retry one course-edition sync."], ["Shared Tutor context", "Remember preferences, recurring work commitments and temporary constraints across local AI and Tutor conversations, after confirmation."], ["Study work", "Track assignments and project milestones, prepare focused practice and compare recorded attendance against course requirements."]].map(([title, copy]) => <div key={title} className="grid gap-1 border-t px-5 py-4 first:border-t-0 sm:grid-cols-[10rem_minmax(0,1fr)] sm:gap-5"><strong className="text-sm">{title}</strong><p className="text-muted-foreground text-sm leading-relaxed">{copy}</p></div>)}</div></DocSection>
        <DocSection id="tools" title="Tool reference" intro="Ask the agent to use the narrowest tool that answers the question. That keeps responses faster and prevents an unrelated workspace-wide search."><div className="border-y"><ToolGroup title="Connect" detail="Current connection and server-supplied workflow guide." tools={["wicker_status", "wicker_guidance"]} /><ToolGroup title="Read" detail="Courses, regulations, material and current study state." tools={["list_courses", "get_course", "get_chapter", "search_course", "list_regulation_sources", "search_regulations", "get_progress", "get_academic_plan", "get_activity", "get_account_summary"]} /><ToolGroup title="Canvas" detail="Assignment feedback, source pages and individual sync controls." tools={["canvas_updates", "canvas_assignment_detail", "canvas_search_announcements", "read_course_source", "prepare_original_download", "read_original_chunk", "canvas_course_materials", "canvas_corpus_status", "canvas_sync_logs", "canvas_sync_control", "canvas_sync_course"]} /><ToolGroup title="Tutor" detail="Saved context and exact actions you approve." tools={["tutor_prepare_context", "tutor_prepare_attendance_update", "tutor_confirm_update", "tutor_forget_context", "tutor_history", "tutor_conversation", "tutor_ask", "tutor_approve_action", "tutor_sources", "tutor_add_source", "tutor_remove_source", "tutor_delete_conversation"]} /><ToolGroup title="Study work" detail="Attendance, tasks, projects and formative readiness." tools={["get_study_work", "get_attendance", "get_course_obligations", "get_study_readiness", "get_weekly_review", "get_study_diagnostic", "answer_study_diagnostic"]} /><ToolGroup title="Practice" detail="Questions and personal learning queues." tools={["list_questions", "get_practice_queue", "list_flashcards", "list_due_cards", "list_mistakes", "list_mock_sessions", "get_mock_session"]} /><ToolGroup title="Write" detail="Requires write scope and explicit confirmation for each individual change." tools={["submit_answer", "set_mastery", "review_card", "create_flashcard", "resolve_mistake", "record_chapter_read", "save_academic_plan", "set_course_visibility"]} /><ToolGroup title="Documents" detail="Reviewable extraction and calendar changes." tools={["analyze_documents", "apply_changes", "get_calendar", "preview_calendar", "save_calendar_link", "sync_calendar_link", "remove_calendar_link"]} /></div></DocSection>
        <DocSection id="two-way" title="Save context and attendance" intro="Your local AI can update the same private record Tutor uses, without calling the hosted Tutor model for a simple memory or attendance change."><ol className="list-decimal space-y-3 pl-5 text-sm leading-relaxed"><li>Read existing context with <code>tutor_sources</code>, or use <code>get_attendance</code> to identify actual completed sessions.</li><li>Prepare the change with <code>tutor_prepare_context</code> or <code>tutor_prepare_attendance_update</code>. The agent shows the exact wording, affected sessions, dates and weekdays.</li><li>After you confirm that individual change, <code>tutor_confirm_update</code> applies the stored review. Reviews expire after 30 minutes; retrying the same confirmed review returns its receipt.</li></ol><p className="mt-4 text-sm leading-relaxed">For example, “I work Tuesdays and Fridays this semester” can be saved as availability with weekdays and an end date. Tutor uses it when advising you; it does not automatically mark classes missed. Preferences, project roles and other context can be saved the same way. Expired context stops contributing to answers.</p><p className="text-muted-foreground mt-3 text-sm leading-relaxed">The MCP workflow guide instructs the agent to proactively propose saving lasting preferences, project decisions and availability learned during your conversation. It checks existing context first and only reports it saved after a successful confirmation receipt. Inspect or remove saved items in <Link className="text-primary underline" href="/app/tutor?view=sources">Tutor → Sources → Remembered context</Link>. A local agent uses <code>tutor_forget_context</code> after a new confirmation. To correct an item, confirm its removal and then confirm the replacement. Attendance is a personal log, not an official university record or an excused-absence decision.</p><p className="text-muted-foreground mt-3 text-sm leading-relaxed">For a project plan, practice set or another supported action, <code>tutor_ask</code> returns a proposal. Review it before <code>tutor_approve_action</code>. This uses the hosted AI allowance. Email drafts stay drafts; the agent cannot send emails or submit work to Canvas.</p></DocSection>
        <DocSection id="canvas-refresh" title="Canvas refresh and retrieval" intro="Choose automatic refresh and its frequency in Settings → Connections → Manage. Defaults are 30 minutes for updates and six hours for materials."><p className="text-sm leading-relaxed">Course selection is recalculated at least hourly, using your academic calendar at period transitions. During summer and other breaks it watches the ending year and newly available next-year courses. Mark your programme completed to pause background work; resume it when studying again. A missing active programme also pauses scheduling. For retakes, automatic refresh selects only the latest eligible edition of each course. Older editions remain searchable and can be synced on demand. Pausing a course stops its automatic collection. Unchanged, versioned resources reuse saved originals and indexes; changed files are collected again.</p><p className="text-muted-foreground mt-3 text-sm leading-relaxed">Use <code>canvas_sync_logs</code> for progress, <code>canvas_sync_control</code> to stop or retry one job, and <code>canvas_sync_course</code> for an exact edition. <Link className="text-primary underline" href="/app/settings/canvas-sync">Canvas sync</Link> exposes the same controls. A recent worker checkpoint is not proof that a file has progressed.</p><p className="text-muted-foreground mt-3 text-sm leading-relaxed">Search announcements as well as slides: a dated, explicit course-team amendment may replace an older coursebook rule. Use <code>read_course_source</code> and its next offset for the actual indexed document. Large datasets receive a labelled search profile; use the preserved original for exact row-level analysis. Assignment links open <Link className="text-primary underline" href="/app/updates?tab=assignments">Updates</Link>, with independently loaded instructions, dates, submission status, rubric and comments.</p></DocSection>
        <DocSection id="feedback" title="Feedback, with control over what you share" intro="Use Feedback in navigation or report an issue from an answer, material, assignment, practice question or sync."><p className="text-sm leading-7">Review the exact report before submitting. You can attach up to four screenshots and paste or edit relevant Tutor conversation text. These attachments and sharing your account email are optional. My feedback shows when the team receives your report, investigation status, completion comments and public replies, lets you withdraw attachments and includes diagnostic preferences.</p><p className="mt-3 text-sm leading-7">Agents use <code>feedback_prepare</code>, show the preview, then obtain fresh approval before <code>feedback_submit</code>. Each reply, rating or withdrawal also requires individual confirmation. Feedback does not write Tutor memory or attendance.</p><a href="/app/feedback" className="mt-3 inline-block text-primary text-sm font-semibold">Open My feedback →</a></DocSection>
        <DocSection id="activity" title="Inspect AI activity" intro="Settings → AI activity records requests that reach Wicker through your personal API keys, starting with this release."><p className="text-sm leading-relaxed">Filter reads, writes and prepared changes; inspect the tool/client, timestamp, HTTP result, duration and confirmed-review reference. One tool may make several requests. A started request with no final result may still be running or may have been interrupted.</p><p className="text-muted-foreground mt-3 text-sm leading-relaxed">Arguments, query text, response contents and credentials are excluded. Client-supplied tool names and confirmation claims are labelled separately from server-confirmed reviews. Local actions that never reach Wicker and earlier requests cannot be reconstructed. Activity is private, included in data export, and removed by account-data erasure.</p><Button className="mt-4" variant="outline" nativeButton={false} render={<Link href="/app/settings?tab=activity" />}>Open AI activity</Button></DocSection>
        <DocSection id="context" title="How context works" intro="The MCP reads the active study workspace rather than a separate agent-only copy."><ul className="space-y-4 text-sm leading-relaxed"><li><strong>Course identity.</strong> Repeated Canvas editions of the same course are aggregated under one course while every source keeps its edition and year provenance.</li><li><strong>Programme rules.</strong> Regulations are indexed once for every programme they govern. <code>search_regulations</code> keeps them separate from course material and returns the document, authority, academic year and page.</li><li><strong>Course lens.</strong> A course code narrows retrieval to that course. Workspace-wide questions can cross courses, calendars, announcements and the planner.</li><li><strong>Conversation memory.</strong> Saved conversations and confirmed context are shared within the active account and programme. Deleted chats are no longer retrieved; removing a context item excludes it from future memory.</li><li><strong>Planner context.</strong> Exam choices, expected grades, electives and what-if decisions are available to Tutor and MCP. Writes use revision checks so an older agent cannot overwrite a newer plan silently.</li><li><strong>Evidence.</strong> Answers can cite maintained material, programme regulations, your private Canvas corpus, uploads, academic record and calendars. Missing evidence should be reported as unknown, not guessed.</li></ul></DocSection>
        <DocSection id="files" title="Files and retrieval" intro="Private Tutor sources retain their originals and searchable passages for later conversations. Academic transcripts and Academic Work documents are handled separately: the browser reads them and saves approved structured results rather than the original file."><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-xl border p-5"><h3 className="text-sm font-semibold">Supported study sources</h3><p className="text-muted-foreground mt-2 text-sm leading-relaxed">PDF, DOCX, images, screenshots, notes and supported course material are extracted into searchable passages while the original remains manageable under Documents → Other uploads. Canvas course material also supports notebooks, code files and ZIPs, spreadsheets and slide decks. Select a material title to preview saved content; use its download icon for the complete original. Hosted agents can call prepare_original_download and use their own HTTP/file tools to stream the original, resume if interrupted, and verify its complete size and SHA-256. The temporary download header grants access only to that file. Links expire after ten minutes; direct downloads support originals up to 1 GiB with a separate 4 GiB daily account budget. The optional local helper offers download_course_original for streaming a file directly to disk (up to 1 GB); its returned path belongs to the helper’s filesystem. Large datasets use labelled search profiles, and Office previews do not reproduce every visual detail.</p></div><div className="rounded-xl border p-5"><h3 className="text-sm font-semibold">Ownership and deletion</h3><p className="text-muted-foreground mt-2 text-sm leading-relaxed">Private uploads and retrieval indexes belong to your account and are removed by data erasure or account deletion. Material already accepted into a shared public library keeps its independent editorial record.</p></div></div></DocSection>
        <DocSection id="permissions" title="Permissions" intro="An OAuth connection or API key acts as you, limited to its approved scopes."><div className="overflow-hidden rounded-xl border"><div className="grid gap-1 px-5 py-4 sm:grid-cols-[7rem_minmax(0,1fr)]"><code>read</code><p className="text-muted-foreground text-sm">Courses, sources, questions, academic state, activity and connection status.</p></div><div className="grid gap-1 border-t px-5 py-4 sm:grid-cols-[7rem_minmax(0,1fr)]"><code>write</code><p className="text-muted-foreground text-sm">Study activity, flashcards, attendance, remembered context and plan changes. The MCP requires explicit confirmation for every individual write; connecting once does not approve future changes.</p></div><div className="grid gap-1 border-t px-5 py-4 sm:grid-cols-[7rem_minmax(0,1fr)]"><code>browser only</code><p className="text-muted-foreground text-sm">Minting or revoking keys, Canvas credentials, data erasure and deleting the account.</p></div></div></DocSection>
        <DocSection id="tokens" title="Access and revocation" intro="OAuth access tokens expire after one hour and refresh automatically when supported by your client. Connections expire after 30 days; sign in again when prompted."><p className="text-sm leading-relaxed">Disconnect an OAuth service to stop its future calls. API keys are separate: removing a client’s local registration does not revoke its saved key. Revoke unused keys in Settings → API access.</p><div className="mt-4 flex flex-wrap gap-3"><Button variant="outline" nativeButton={false} render={<Link href="/connect/remote" />}>Manage connected services</Button><Button variant="ghost" nativeButton={false} render={<Link href="/app/settings?tab=api" />}>Manage API keys</Button></div></DocSection>
        <DocSection id="troubleshooting" title="Troubleshooting"><div className="border-y">{[["The server already exists", "Use the migration commands above to replace its registration. For Claude Code, remove it from the scope where it was originally installed. Check project overrides."], ["The agent cannot see Wicker", "Restart the agent after registration. Check the HTTPS server URL, complete OAuth sign-in, then call wicker_status. Node.js is required only for the optional npm helper."], ["Authentication expired or was rejected", "Sign in again with codex mcp login wicker-study, or open /mcp in Claude Code and re-authenticate. For API-key connections, check the key’s server, expiry and revocation in API access settings."], ["A course has no material", "Check Canvas sync first. A failed priority extraction does not mean indexed material is missing; it affects structured obligations."], ["The answer searches too broadly", "Name the course or pass its course code. Course-scoped tools should not widen to the full workspace unless the question crosses courses."], ["A write conflicts or its result is uncertain", "Read the current record and receipt before preparing another change. Do not blindly reapply it. A new or expired review needs fresh confirmation."], ["New tools are missing", "Reconnect the hosted client to refresh tool discovery, then call wicker_guidance. Only optional package users need to update their npm version. No separate workflow-guide download is needed."], ["A request was limited", "Respect Retry-After before retrying and narrow the request or reduce concurrency. MCP transport budgets are separate from your agent provider’s model usage."]].map(([title, copy]) => <details key={title} className="border-t first:border-t-0"><summary className="cursor-pointer px-1 py-4 text-sm font-semibold">{title}</summary><p className="text-muted-foreground px-1 pb-4 text-sm leading-relaxed">{copy}</p></details>)}</div></DocSection>
        <DocSection id="local-generation" title="Generate a study guide locally" intro="Use your local agent through the hosted MCP to process course material and generate chapters, visuals and practice. No Wicker package is required. Your local subscription or model costs apply; these steps do not spend Wicker's AI allowance."><p className="text-sm text-muted-foreground">Choose Local agent through MCP when creating a guide, then copy its continuation instruction into your agent. Each step receives the platform’s current teaching prompt, evidence and structure. Results return to the same reader after schema, citation and teaching checks. Local review is supplied by your agent; it is not independent editorial review.</p><p className="mt-3 text-sm text-muted-foreground">Existing guides stay readable during generation. Reconnect your MCP client after updating to discover the local-generation tools. The tools fetch current pipeline instructions automatically.</p></DocSection>
        <DocSection id="http" title="HTTP API" intro="The web app and MCP use the same scoped JSON API. The live manifest is the versioned source of truth for endpoint paths, bodies and required scopes."><p className="mb-4 text-sm leading-relaxed">Call <code>wicker_guidance</code> for the current workflow guide. The optional <a className="text-primary underline" href="/skills/wicker-study/SKILL.md">discovery skill</a> helps an agent find that guide; it does not need a separate update for pipeline changes.</p><div className="flex flex-wrap gap-3"><Button variant="outline" nativeButton={false} render={<a href="/api/agent/manifest" target="_blank" rel="noreferrer" />}>Open live manifest<ExternalLinkIcon data-icon="inline-end" /></Button></div></DocSection>
        <p id="local-tools" className="scroll-mt-8 border-t pt-6 text-sm text-muted-foreground">Maintaining editorial content or running bulk imports? See the <Link className="text-primary underline" href="/docs#admin">administrator toolkit documentation</Link>. Student setup, original downloads and local generation use the hosted connection above.</p>
      </article>
    </div>
  </div>;
}
