'use client'
import { STUDY_GENERATION_LIMITS } from '@/lib/study-generation-limits.mjs'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet'
import { Button } from '@/components/ui/button'
import { studyRequest, type StudyCourseIdentity } from '@/lib/workspace/study-versions'

type Settings = {enabled:boolean;execution:'local'|'hosted';rule:'auto'|'weekly'|'topic'|'textbook';historicalMode:'none'|'suggest'|'supplement';supportingSourceKeys:string[];billing:{source:'platform'|'personal';quality:'standard'|'enhanced'|'sol'|'astra';maxJobUsd:number}}
type Status = {settings:Settings;checkedAt:string|null;error:string|null;modules:{identity:string;title:string;organisation:string;status:string;historicalSuggestions?:{key:string;title:string;academicYear:string}[];blockers:string[];reasons:string[];error?:string;generationStatus?:string;url?:string;decision?:{ready:boolean;reason:string;missingReadings:string[];unresolvedTopics:string[]}}[];sources:{key:string;title:string;academicYear:string}[]}
export function CourseGuideAutomation({course,onSaved}:{course:StudyCourseIdentity;onSaved:()=>void}) {
  const [open,setOpen]=useState(false)
  const [data,setData]=useState<Status|null>(null),[settings,setSettings]=useState<Settings|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  const query=new URLSearchParams(course).toString()
  useEffect(()=>{let active=true;setData(null);setSettings(null);setError('');studyRequest<Status>(`/api/study-versions/module-guides?${query}`).then(r=>{if(active){setData(r);setSettings(r.settings)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[query])
  async function save(){if(!settings)return;setBusy(true);setError('');try{const r=await studyRequest<Status>('/api/study-versions/module-guides',{course,settings});setData(r);setSettings(r.settings);onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <div className="course-band border-t py-5">
    <Button variant="outline" size="sm" onClick={()=>setOpen(true)}>Automatic module guides {data?.settings.enabled ? '· on' : '· off'}</Button>
    <Sheet open={open} onOpenChange={setOpen}><SheetContent className="data-[side=right]:w-full data-[side=right]:sm:max-w-2xl"><SheetHeader className="border-b p-6"><SheetTitle>Automatic module guides</SheetTitle><SheetDescription>{course.courseName} · {course.academicYear}</SheetDescription></SheetHeader>
    <div className="min-h-0 space-y-5 overflow-y-auto p-6 text-sm">
      <p className="text-muted-foreground">Infer when each module has enough material to teach, then prepare a private guide. New files, edits and exam-scope announcements trigger updates. Your previous revision stays available while the replacement is checked.</p>
      {error&&<p role="alert" className="text-destructive">{error}</p>}
      {!settings&&!error&&<p role="status">Loading automatic guide settings…</p>}
      {settings&&<>
        <label className="flex items-center gap-2"><input type="checkbox" checked={settings.enabled} onChange={e=>setSettings({...settings,enabled:e.target.checked})}/>Prepare and maintain module guides automatically</label>
        <div className="flex flex-wrap gap-4">
          <label className="space-y-2">Generation<select aria-label="Automatic guide generation" className="block rounded-md border bg-card px-3 py-2" value={settings.execution} onChange={e=>setSettings({...settings,execution:e.target.value as Settings['execution']})}><option value="local">My connected MCP agent</option><option value="hosted">In-app background generation</option></select></label>
          <label className="space-y-2">Course structure<select aria-label="Course structure" className="block rounded-md border bg-card px-3 py-2" value={settings.rule} onChange={e=>setSettings({...settings,rule:e.target.value as Settings['rule']})}><option value="auto">Infer from the materials</option><option value="weekly">Weekly modules</option><option value="topic">Topic modules</option><option value="textbook">Textbook-led modules</option></select></label>
        </div>
        {settings.execution==='local'?<p className="text-muted-foreground">Work waits in the MCP generation queue until your agent runs it. New revisions use this mode; existing runs keep their original choice. Your subscription must be available there; Wicker does not use platform AI as a fallback.</p>:<div className="flex flex-wrap items-end gap-4"><label>Pay with<select aria-label="Automatic guide billing" className="mt-2 block rounded-md border bg-card px-3 py-2" value={settings.billing.source} onChange={e=>setSettings({...settings,billing:{...settings.billing,source:e.target.value as 'platform'|'personal'}})}><option value="platform">Platform allowance</option><option value="personal">My API key</option></select></label>{settings.billing.source==='platform' && <label>Generation model<select aria-label="Automatic guide model" className="mt-2 block rounded-md border bg-card px-3 py-2" value={settings.billing.quality} onChange={e=>setSettings({...settings,billing:{...settings.billing,quality:e.target.value as Settings['billing']['quality']}})}><option value="standard">Configured platform model</option><option value="sol">GPT-5.6 Sol</option><option value="astra">GPT-6 Astra</option><option value="enhanced">GPT-5.4</option></select></label>}<label>Maximum per revision (USD)<input aria-label="Automatic guide spending cap" type="number" min="0.05" max={STUDY_GENERATION_LIMITS.maxJobUsd} step="0.05" className="mt-2 block w-32 rounded-md border bg-card px-3 py-2" value={settings.billing.maxJobUsd} onChange={e=>setSettings({...settings,billing:{...settings.billing,maxJobUsd:Number(e.target.value)}})}/></label><p className="text-xs text-muted-foreground">Existing account limits also apply. Each material update may create a new revision.</p></div>}
        <label className="block">Past-year materials<select aria-label="Past-year materials" className="mt-2 block max-w-full rounded-md border bg-card px-3 py-2" value={settings.historicalMode||'suggest'} onChange={e=>setSettings({...settings,historicalMode:e.target.value as Settings['historicalMode']})}><option value="suggest">Suggest matching material</option><option value="supplement">Supplement matching topics automatically</option><option value="none">Only readings I select</option></select><span className="mt-2 block text-xs text-muted-foreground">Current-year sources must establish the topic scope. Older material can explain those topics; it cannot supply current exam rules or prove complete coverage.</span></label>
        <details><summary className="cursor-pointer">Supporting readings and textbook excerpts</summary><p className="my-3 text-muted-foreground">Choose readable excerpts needed across modules, including an older textbook edition if appropriate. A book title or link is insufficient. Add missing chapters through Create study guide → sources, or your MCP agent, then reload this page.</p><div className="max-h-56 space-y-2 overflow-auto">{data?.sources.map(s=><label key={s.key} className="flex items-start gap-2"><input type="checkbox" className="mt-1" checked={settings.supportingSourceKeys.includes(s.key)} onChange={e=>setSettings({...settings,supportingSourceKeys:e.target.checked?[...settings.supportingSourceKeys,s.key]:settings.supportingSourceKeys.filter(k=>k!==s.key)})}/><span>{s.title} <small className="text-muted-foreground">{s.academicYear}</small></span></label>)}</div></details>
        <Button size="sm" disabled={busy} onClick={()=>void save()}>{busy?'Saving…':'Save automatic guide settings'}</Button>
      </>}
      {data?.error&&<p role="status" className="text-muted-foreground">{data.error}</p>}
      {!!data?.modules.length&&<ul className="divide-y">{data.modules.map(m=><li key={m.identity} className="space-y-2 py-3"><div className="flex flex-wrap justify-between gap-3"><strong>{m.title}</strong>{m.url&&<Link className="text-primary underline" href={m.url}>View guide progress</Link>}</div><p className="text-muted-foreground">{m.organisation} · {m.generationStatus || m.status}</p>{!!m.historicalSuggestions?.length&&<p className="text-xs text-muted-foreground">Possible past-year support: {m.historicalSuggestions.map(s=>`${s.title} (${s.academicYear})`).join('; ')}. Select relevant readings above, or enable automatic supplementation.</p>}{[...m.blockers,...m.reasons,m.error,m.decision?.reason,...(m.decision?.missingReadings||[]),...(m.decision?.unresolvedTopics||[])].filter(Boolean).map((reason,i)=><p key={i} className="text-xs leading-5 text-muted-foreground">{reason}</p>)}</li>)}</ul>}
      <p className="text-xs text-muted-foreground">Readiness is an inference about the materials, not mastery. Missing readings or uncertain scope pause generation. {data?.checkedAt?`Last checked ${new Date(data.checkedAt).toLocaleString()}.`:''}</p>
    </div>
    </SheetContent></Sheet>
  </div>
}
