'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet'
import { Button } from '@/components/ui/button'
import { CanvasRefreshSettings, type RefreshSettings } from './canvas-refresh-settings'
import { useJson } from '@/components/workspace/use-json'
import { studyRequest, type StudyCourseIdentity } from '@/lib/workspace/study-versions'

type Policy={guides:boolean;papers:boolean;priorities:boolean}
type Status={settings:Policy;courses:{course:StudyCourseIdentity;settings:{enabled:boolean;execution:string;[key:string]:unknown};checkedAt?:string;error?:string;modules:number}[];events:{at:string;courseCode:string;message:string;details?:{title:string;status:string;reasons:string[];error?:string}[]}[];jobs:{id:string;title:string;courseCode:string;kind:string;status:string;stage:string;error?:string;updatedAt:string;url:string}[]}
export function RecurringPipelinesTab(){
  const connections=useJson<{connections:{origin:string;corpus?:{collectionEnabled:boolean;refresh?:RefreshSettings}}[]}>('/api/account/integrations/canvas')
  const [host,setHost]=useState<string|null>(null)
  const [data,setData]=useState<Status|null>(null),[settings,setSettings]=useState<Policy|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0)
  useEffect(()=>{let active=true,pending=false;const load=async()=>{if(pending)return;pending=true;try{const r=await studyRequest<Status>('/api/study-versions/pipelines');if(active){setData(r);setSettings(s=>s||r.settings);setError('')}}catch(e){if(active)setError((e as Error).message)}finally{pending=false}};void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load()},10000);return()=>{active=false;clearInterval(timer)}},[revision])
  async function save(){if(!settings)return;setBusy(true);try{setData(await studyRequest<Status>('/api/study-versions/pipelines',{settings}));setError('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <div className="max-w-5xl space-y-8">
    <header><h2 className="text-xl font-semibold">Recurring pipelines</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">Control automatic collection and processing. Pausing keeps saved materials and progress. A model call already in flight may finish its current checkpoint; subsequent calls wait until enabled again.</p></header>
    {error&&<p role="alert" className="text-destructive">{error}</p>}
    {connections.error&&<p role="alert" className="text-destructive">{connections.error}</p>}
    <section><h3 className="font-semibold">Canvas materials and announcements</h3>{connections.data?.connections.map(c=><div key={c.origin} className="mt-4"><p className="text-sm text-muted-foreground">{c.origin}</p><Button variant="outline" size="sm" className="mt-2" onClick={()=>setHost(c.origin)}>Configure refresh schedule</Button><Sheet open={host===c.origin} onOpenChange={open=>{if(!open)setHost(null)}}><SheetContent className="data-[side=right]:w-full data-[side=right]:sm:max-w-2xl"><SheetHeader className="border-b p-6"><SheetTitle>Canvas refresh schedule</SheetTitle><SheetDescription>{c.origin}</SheetDescription></SheetHeader><div className="min-h-0 overflow-y-auto p-6"><CanvasRefreshSettings key={JSON.stringify(c.corpus?.refresh)} origin={c.origin} saved={c.corpus?.refresh} collectionEnabled={!!c.corpus?.collectionEnabled} onSaved={connections.reload}/></div></SheetContent></Sheet></div>)}{connections.data&&!connections.data.connections.length&&<p className="mt-3 text-sm text-muted-foreground">Connect Canvas and enable material collection in <Link className="underline" href="/app/settings?tab=connections">Connections</Link>.</p>}<div className="mt-4 flex flex-wrap gap-5 text-sm"><Link className="text-primary underline" href="/app/settings/canvas-sync">Sync history and retries</Link><Link className="text-primary underline" href="/app/settings/canvas-sync/logs">Canvas and course-rule logs</Link></div></section>
    <section className="border-t pt-6"><h3 className="font-semibold">Processing after collection</h3>{settings?<div className="mt-4 space-y-4">{([['priorities','Attendance and priority rules','Recheck saved course rules daily, after material refreshes, and after extractor updates.'],['papers','Mock exams and practice sheets','Extract new or modified papers into the practice library.'],['guides','Module guides and revisions','Check inferred readiness and update automatically maintained guides when source material or exam scope changes.']] as const).map(([key,label,description])=><label key={key} className="flex items-start gap-3"><input className="mt-1 size-4" type="checkbox" checked={settings[key]} onChange={e=>setSettings({...settings,[key]:e.target.checked})}/><span><strong className="text-sm font-medium">{label}</strong><span className="mt-1 block text-sm text-muted-foreground">{description}</span></span></label>)}<Button size="sm" disabled={busy} onClick={()=>void save()}>{busy?'Saving…':'Save pipeline controls'}</Button></div>:<p className="mt-4 text-sm" role="status">Loading pipeline controls…</p>}</section>
    <section className="border-t pt-6"><h3 className="font-semibold">Automatic guides by course</h3><p className="mt-2 text-sm text-muted-foreground">Choose a generation mode and textbook readings on each course’s Study guides page. Local jobs wait for your MCP agent. Readiness is inferred from materials, never a claim of student mastery.</p><ul className="mt-4 divide-y">{data?.courses.map((c,i)=><li key={i} className="flex flex-wrap items-start justify-between gap-4 py-4"><div><Link className="font-medium text-primary underline" href={`/app/courses/${encodeURIComponent(c.course.courseCode)}?year=${encodeURIComponent(c.course.academicYear)}`}>{c.course.courseName} · {c.course.academicYear}</Link><p className="mt-1 text-sm text-muted-foreground">{c.settings.execution==='local'?'MCP agent':'Background generation'} · {c.modules} modules {c.checkedAt?`· checked ${new Date(c.checkedAt).toLocaleString()}`:''}</p>{c.error&&<p className="mt-1 text-sm text-destructive">{c.error}</p>}</div><Button variant="outline" size="sm" disabled={busy} onClick={async()=>{setBusy(true);try{await studyRequest('/api/study-versions/module-guides',{course:c.course,settings:{...c.settings,enabled:!c.settings.enabled}});setRevision(n=>n+1)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{c.settings.enabled?'Turn off':'Turn on'}</Button></li>)}</ul>{data&&!data.courses.length&&<p className="mt-4 text-sm text-muted-foreground">No courses configured yet.</p>}</section>
    <section className="border-t pt-6"><div className="flex justify-between gap-4"><h3 className="font-semibold">Processing jobs</h3><Button variant="ghost" size="sm" onClick={()=>setRevision(n=>n+1)}>Refresh status</Button></div><p className="mt-2 text-xs text-muted-foreground">Updates every 10 seconds while this page is visible. Times reflect saved progress, not a worker heartbeat. Shows the latest 100 jobs.</p><ul className="mt-3 divide-y">{data?.jobs.map(j=><li key={j.id} className="space-y-1 py-3"><Link className="text-sm font-medium text-primary underline" href={j.url}>{j.courseCode} · {j.title}</Link><p className="text-xs text-muted-foreground">{j.kind} · {j.status==='waiting-local'||j.status==='local-ready'?'Waiting for local agent':j.status} · {j.stage} · {new Date(j.updatedAt).toLocaleString()}</p>{j.error&&<p className="text-sm text-destructive">{j.error}</p>}</li>)}</ul>{data&&!data.jobs.length&&<p className="mt-3 text-sm text-muted-foreground">No processing jobs recorded.</p>}</section>
    <section className="border-t pt-6"><h3 className="font-semibold">Guide check logs</h3><p className="mt-2 text-xs text-muted-foreground">Latest 100 events; up to 50 retained checks per course. Open a guide job for its review findings.</p><ul className="mt-3 divide-y">{data?.events.map((e,i)=><li key={i} className="py-3"><p className="text-xs text-muted-foreground">{new Date(e.at).toLocaleString()} · {e.courseCode}</p><p className="mt-1 text-sm">{e.message}</p>{!!e.details?.length&&<details className="mt-2 text-sm"><summary className="cursor-pointer">Read module decisions</summary><ul className="mt-2 space-y-2">{e.details.map((d,j)=><li key={j}><strong>{d.title}</strong> · {d.status}{[...d.reasons,d.error].filter(Boolean).map((r,k)=><p key={k} className="text-muted-foreground">{r}</p>)}</li>)}</ul></details>}</li>)}</ul>{data&&!data.events.length&&<p className="mt-3 text-sm text-muted-foreground">No guide checks recorded yet.</p>}</section>
  </div>
}
