import type { Metadata } from 'next'
import { ContactLink } from '@/components/site/contact-link'
import { operatorName } from '@/lib/site-content'

export const metadata: Metadata = { title: 'Privacy notice' }

export default function PrivacyPage() {
  return (
    <main id="main-content" className="legal-page">
      <header className="legal-hero">
        <div><h1>Privacy notice</h1><p>How Wicker Study handles personal data, and how to exercise your rights.</p></div>
        <dl><div><dt>Effective</dt><dd>6 September 2026</dd></div><div><dt>Controller</dt><dd>{operatorName}</dd></div><div><dt>Contact</dt><dd><ContactLink kind="privacy" /></dd></div></dl>
      </header>
      <div className="legal-layout">
        <nav aria-label="Privacy notice sections"><a href="#controller">Controller</a><a href="#data">Data we process</a><a href="#purposes">Purposes and legal bases</a><a href="#providers">Service providers</a><a href="#retention">Retention</a><a href="#rights">Your rights</a><a href="#cookies">Cookies</a><a href="#contact">Contact</a></nav>
        <article>
          <section id="controller"><h2>1. Controller</h2><p>Wicker Study is operated by {operatorName}, acting as an individual rather than through a company or other legal entity. {operatorName} is the controller for personal data processed through this service. Privacy enquiries and data-rights requests can be sent to <ContactLink kind="privacy" />; general enquiries can be sent to <ContactLink kind="info" />.</p></section>
          <section id="data"><h2>2. Data we process</h2><ul><li><strong>Account data:</strong> account identifier, email address, authentication status, and account creation information supplied through Clerk.</li><li><strong>Study data:</strong> course ordering, progress, mastery, notes, attempts, answers, flashcards, mistake history, review schedules, academic-plan details, and mock-session records.</li><li><strong>Course requests:</strong> the course and curriculum context, notes, URLs, and source files you choose to submit when requesting maintained content for an unsupported course, plus the request’s production status.</li><li><strong>Optional editorial contributions:</strong> if you separately opt in, the selected rights basis, permission time, review decision, source filename, checksum, extracted text, page-level provenance, topic mappings, and evidence links needed to prepare and audit shared course content.</li><li><strong>AI activity:</strong> tutor messages, exercise instructions, academic documents or descriptions submitted for plan extraction, retrieved course passages, request counts, and input/output token totals. Account email addresses are not intentionally included in model prompts.</li><li><strong>Feedback:</strong> reports, optionally shared account email for investigation follow-up, explicitly attached excerpts/screenshots, answer ratings, public replies, review status and access records. Unsubmitted drafts, optional contact email and attachments are encrypted. Minimized diagnostics contain error codes, page categories, timing and release; diagnostic and optional performance preferences are available in My feedback. Optional AI review uses only submitted messages/text excerpts after per-report permission, never referenced private originals.</li><li><strong>Correspondence:</strong> messages and contact details supplied when someone emails a Wicker Study contact address.</li><li><strong>Technical data:</strong> essential session data and security or service logs created by hosting and authentication providers.</li></ul><p>Course-request material is private intake by default. Optional shared use is presented separately and is not required to request a course. Source originals remain restricted to authorised administrators; student-facing publication uses reviewed derivatives rather than automatically exposing uploaded files.</p></section>
          <section id="purposes"><h2>3. Purposes and legal bases</h2><div className="legal-table"><div><strong>Provide the workspace</strong><span>Account access, synchronisation, progress, practice, requested AI features, and receiving and producing requested private course content.</span><em>Performance of the service contract</em></div><div><strong>Prepare shared course content</strong><span>Extract, index, map, generate, quality-review, and maintain evidence-grounded course derivatives from sources you separately offer for this purpose.</span><em>Your optional permission and the contribution terms you accept</em></div><div><strong>Keep the service secure</strong><span>Authentication, abuse prevention, rate limiting, troubleshooting, and operational integrity.</span><em>Legitimate interests and legal obligations where applicable</em></div><div><strong>Answer enquiries</strong><span>Support, privacy, security, legal, and general correspondence.</span><em>Performance of the service contract, legitimate interests, or legal obligations depending on the request</em></div><div><strong>Respond to rights requests</strong><span>Access, correction, export, restriction, objection, and deletion requests.</span><em>Legal obligation</em></div></div></section>
          <section id="providers"><h2>4. Service providers and transfers</h2><p>Wicker Study uses Clerk for authentication, Neon for managed database storage, Vercel for hosting, OpenAI for requested AI features, Forward Email for incoming email forwarding, and Google Gmail as the destination mailbox for Wicker Study contact addresses. These providers process only the data needed for their role. Some processing may occur outside the EEA under the applicable provider terms, data-processing agreements, adequacy decisions, or other recognised transfer safeguards.</p><p>Personal data is not sold and is not used for third-party advertising.</p></section>
          <section id="feedback-retention"><h2>Feedback retention</h2><p>Feedback drafts expire after 30 minutes and are purged after one day. Minimized diagnostic events are kept for 30 days. Shared evidence is removed 90 days after issue closure, and closed reports after 12 months. You can withdraw attachments sooner in My feedback. Account export and deletion include your feedback data. Deleting live data does not retroactively remove copies from infrastructure backups before their normal expiry. Feedback is used for service support and improvement, with optional model-assisted review only when you choose it.</p></section><section id="retention"><h2>5. Retention, withdrawal, and deletion</h2><p>Primary account and study data is retained while the account remains active. Academic Work and transcript originals attached in setup are retained privately so you can view and download them later. They are removed when you remove that document, erase uploaded data, or delete your account. Their bytes are kept separate from AI context. Other curriculum and screenshot originals submitted for plan extraction are used to create a review draft and are not retained; only confirmed academic fields are saved. Files attached to a course-content request remain private while the request is processed and are included in account export and deletion.</p><p>You can withdraw optional shared-use permission from the course request while it is in production, or contact <ContactLink kind="privacy" />. Withdrawal excludes that contribution from future mapping, generation, and publication and does not affect processing that was lawful before withdrawal. Account deletion withdraws the account’s sources from future editorial processing and removes an uploaded source when no independently authorised contribution still supplies the same file. Already-published reviewed derivatives may remain where they contain no personal data and their continued use is permitted by the contribution terms; a privacy or rights request can still ask us to assess a specific item.</p><p>Correspondence is kept only as long as reasonably needed to handle the request, maintain necessary records, and meet legal obligations. Users can export personal data and permanently delete an account from Settings. Limited copies may remain temporarily in provider backups or security logs until their normal protected retention cycle ends, or longer where law requires it.</p></section>
          <section id="rights"><h2>6. Your rights</h2><p>Depending on the circumstances, the GDPR provides rights to be informed, access data, correct inaccurate data, request erasure or restriction, object to certain processing, receive portable data, and avoid decisions based solely on automated processing that have legal or similarly significant effects.</p><p>Settings provides direct data export and account deletion. Other requests can be sent to <ContactLink kind="privacy" />. We may need to verify identity and aim to respond without undue delay and ordinarily within one month. You may also complain to the data protection authority in your country, including the <a href="https://autoriteitpersoonsgegevens.nl/en" rel="noreferrer">Dutch Data Protection Authority</a> where applicable.</p></section>
          <section id="automation"><h2>7. AI and automated processing</h2><p>AI features support study and do not make legal or similarly significant decisions about users. Routine answer checking is performed locally against prepared reference material. Tutor chat is retrieval-grounded, but its output can still be incomplete or incorrect and should be checked against course sources. Academic-plan extraction creates an editable draft only; users review and confirm the fields before they enter the personal record. Shared-course generation is started by an administrator, produces private drafts with source evidence, and requires editorial approval before publication. Assessment rules that are missing, uncertain, or contradictory remain marked for review.</p></section>
          <section id="cookies"><h2>8. Cookies and local storage</h2><p>The service uses essential authentication storage and local browser storage needed to maintain sessions, interface preferences, and study continuity. Wicker Study does not currently use advertising cookies or third-party analytics trackers. If non-essential tracking is introduced, this notice and the consent experience will be updated first.</p></section>
          <section id="security"><h2>9. Security</h2><p>Personal data is separated by authenticated user identifier. Transport encryption, access controls, managed infrastructure, and server-side policy enforcement are used to reduce risk. No internet service can guarantee absolute security.</p></section>
          <section id="contact"><h2>10. Contact and changes</h2><p>Privacy questions and rights requests: <ContactLink kind="privacy" />. Security reports: <ContactLink kind="security" />. General enquiries: <ContactLink kind="info" />. Material changes to this notice will be dated on this page.</p></section>
        </article>
      </div>
    </main>
  )
}
