import type { Metadata } from 'next'
import { ContactLink } from '@/components/site/contact-link'
import { operatorName } from '@/lib/site-content'

export const metadata: Metadata = { title: 'Privacy notice' }

export default function PrivacyPage() {
  return (
    <main id="main-content" className="legal-page">
      <header className="legal-hero">
        <div><h1>Privacy notice</h1><p>How Wicker Study handles personal data, and how to exercise your rights.</p></div>
        <dl><div><dt>Effective</dt><dd>30 August 2026</dd></div><div><dt>Controller</dt><dd>{operatorName}</dd></div><div><dt>Contact</dt><dd><ContactLink kind="privacy" /></dd></div></dl>
      </header>
      <div className="legal-layout">
        <nav aria-label="Privacy notice sections"><a href="#controller">Controller</a><a href="#data">Data we process</a><a href="#purposes">Purposes and legal bases</a><a href="#providers">Service providers</a><a href="#retention">Retention</a><a href="#rights">Your rights</a><a href="#cookies">Cookies</a><a href="#contact">Contact</a></nav>
        <article>
          <section id="controller"><h2>1. Controller</h2><p>Wicker Study is operated by {operatorName}, acting as an individual rather than through a company or other legal entity. {operatorName} is the controller for personal data processed through this service. Privacy enquiries and data-rights requests can be sent to <ContactLink kind="privacy" />; general enquiries can be sent to <ContactLink kind="info" />.</p></section>
          <section id="data"><h2>2. Data we process</h2><ul><li><strong>Account data:</strong> account identifier, email address, authentication status, and account creation information supplied through Clerk.</li><li><strong>Study data:</strong> course ordering, progress, mastery, notes, attempts, answers, flashcards, mistake history, review schedules, academic-plan details, and mock-session records.</li><li><strong>Course requests:</strong> the course and curriculum context, notes, URLs, and source files you choose to submit when requesting maintained content for an unsupported course, plus the request’s production status.</li><li><strong>AI activity:</strong> tutor messages, exercise instructions, academic documents or descriptions submitted for plan extraction, retrieved course passages, request counts, and input/output token totals. Account email addresses are not intentionally included in model prompts.</li><li><strong>Correspondence:</strong> messages and contact details supplied when someone emails a Wicker Study contact address.</li><li><strong>Technical data:</strong> essential session data and security or service logs created by hosting and authentication providers.</li></ul><p>Published shared course sources are editorial content and are stored separately from personal study records. Materials attached to a course request remain private intake sources unless an administrator separately verifies that they may be used in a published editorial release.</p></section>
          <section id="purposes"><h2>3. Purposes and legal bases</h2><div className="legal-table"><div><strong>Provide the workspace</strong><span>Account access, synchronisation, progress, practice, requested AI features, and receiving and producing requested course content.</span><em>Performance of the service contract</em></div><div><strong>Keep the service secure</strong><span>Authentication, abuse prevention, rate limiting, troubleshooting, and operational integrity.</span><em>Legitimate interests and legal obligations where applicable</em></div><div><strong>Answer enquiries</strong><span>Support, privacy, security, legal, and general correspondence.</span><em>Performance of the service contract, legitimate interests, or legal obligations depending on the request</em></div><div><strong>Respond to rights requests</strong><span>Access, correction, export, restriction, objection, and deletion requests.</span><em>Legal obligation</em></div></div></section>
          <section id="providers"><h2>4. Service providers and transfers</h2><p>Wicker Study uses Clerk for authentication, Neon for managed database storage, Vercel for hosting, OpenAI for requested AI features, Forward Email for incoming email forwarding, and Google Gmail as the destination mailbox for Wicker Study contact addresses. These providers process only the data needed for their role. Some processing may occur outside the EEA under the applicable provider terms, data-processing agreements, adequacy decisions, or other recognised transfer safeguards.</p><p>Personal data is not sold and is not used for third-party advertising.</p></section>
          <section id="retention"><h2>5. Retention and deletion</h2><p>Primary account and study data is retained while the account remains active. Curriculum, transcript, and screenshot originals submitted for plan extraction are used to create a review draft and are not retained by Wicker Study; only academic fields the user confirms are saved. In contrast, files intentionally attached to a course-content request are retained privately while the request is processed and are included in account export and deletion. Administrators may remove them sooner when no longer needed. Correspondence is kept only as long as reasonably needed to handle the request, maintain necessary records, and meet legal obligations. Users can export their personal data and permanently delete their account from Settings. Deletion removes the active personal record, course-request intake files, and authentication identity; limited copies may remain temporarily in provider backups or security logs until their normal protected retention cycle ends, or longer where law requires it.</p></section>
          <section id="rights"><h2>6. Your rights</h2><p>Depending on the circumstances, the GDPR provides rights to be informed, access data, correct inaccurate data, request erasure or restriction, object to certain processing, receive portable data, and avoid decisions based solely on automated processing that have legal or similarly significant effects.</p><p>Settings provides direct data export and account deletion. Other requests can be sent to <ContactLink kind="privacy" />. We may need to verify identity and aim to respond without undue delay and ordinarily within one month. You may also complain to the data protection authority in your country, including the <a href="https://autoriteitpersoonsgegevens.nl/en" rel="noreferrer">Dutch Data Protection Authority</a> where applicable.</p></section>
          <section id="automation"><h2>7. AI and automated processing</h2><p>AI features support study and do not make legal or similarly significant decisions about users. Routine answer checking is performed locally against prepared reference material. Tutor chat is retrieval-grounded, but its output can still be incomplete or incorrect and should be checked against course sources. Academic-plan extraction creates an editable draft only; users review and confirm the fields before they enter the personal record.</p></section>
          <section id="cookies"><h2>8. Cookies and local storage</h2><p>The service uses essential authentication storage and local browser storage needed to maintain sessions, interface preferences, and study continuity. Wicker Study does not currently use advertising cookies or third-party analytics trackers. If non-essential tracking is introduced, this notice and the consent experience will be updated first.</p></section>
          <section id="security"><h2>9. Security</h2><p>Personal data is separated by authenticated user identifier. Transport encryption, access controls, managed infrastructure, and server-side policy enforcement are used to reduce risk. No internet service can guarantee absolute security.</p></section>
          <section id="contact"><h2>10. Contact and changes</h2><p>Privacy questions and rights requests: <ContactLink kind="privacy" />. Security reports: <ContactLink kind="security" />. General enquiries: <ContactLink kind="info" />. Material changes to this notice will be dated on this page.</p></section>
        </article>
      </div>
    </main>
  )
}
