import { test, expect } from '@playwright/test'

test('signed-out remote connection has visible controls and preserves the approval return route', async ({ page }) => {
  await page.route('**/api/mcp/consent?**', route => route.fulfill({status:401,json:{error:'Sign in required'}}))
  await page.goto('/connect/remote?request=approval-fixture')
  const signIn=page.getByRole('link',{name:'Sign in to continue'})
  await expect(signIn).toBeVisible()
  await expect(signIn).toHaveAttribute('href','/sign-in?redirect_url=%2Fconnect%2Fremote%3Frequest%3Dapproval-fixture')
  const style=await signIn.evaluate(node=>({background:getComputedStyle(node).backgroundColor,height:node.getBoundingClientRect().height,padding:getComputedStyle(node.closest('section').querySelector('header')).paddingTop}))
  expect(style.background).toBe('rgb(63, 81, 217)')
  expect(style.height).toBeGreaterThanOrEqual(44)
  expect(parseFloat(style.padding)).toBeGreaterThanOrEqual(24)
  await signIn.focus()
  expect(await signIn.evaluate(node=>getComputedStyle(node).outlineStyle)).toBe('solid')
  await page.setViewportSize({width:390,height:844})
  await expect(signIn).toBeInViewport()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await signIn.click()
  await expect(page).toHaveURL(/\/sign-in\?redirect_url=%2Fconnect%2Fremote%3Frequest%3Dapproval-fixture/)
  await expect(page.getByRole('heading',{name:'Return to your study record.'})).toBeVisible()
})

test('remote connection distinguishes a failed list from an empty one and reviews exact permissions',async({page})=>{
  await page.route('**/api/mcp/connections',route=>route.fulfill({status:503,json:{error:'Connections are temporarily unavailable.'}}))
  await page.goto('/connect/remote')
  await expect(page.locator('main').getByRole('alert')).toContainText('temporarily unavailable')
  await expect(page.getByText('No services connected yet.')).toHaveCount(0)
  await page.unroute('**/api/mcp/connections')
  await page.route('**/api/mcp/connections',route=>route.fulfill({json:{account:{id:'fixture-user',email:'student@example.test'},connections:[{id:'fixture',name:'Research workspace',scopes:['read'],createdAt:'2026-09-08T00:00:00Z'}]}}))
  await page.reload()
  await expect(page.getByText('Research workspace',{exact:true})).toBeVisible()
  await expect(page.getByRole('button',{name:'Disconnect',exact:true})).toBeVisible()
  await page.route('**/api/mcp/consent?**',route=>route.fulfill({json:{name:'Research workspace',redirectUri:'https://example.org/callback',scopes:['read','write'],account:{id:'fixture-user',email:'student@example.test'}}}))
  await page.goto('/connect/remote?request=approval-fixture')
  await expect(page.getByRole('heading',{name:'Connect Research workspace?'})).toBeVisible()
  await expect(page.getByText('Read your study data',{exact:true})).toBeVisible()
  await expect(page.getByText('Make study changes',{exact:true})).toBeVisible()
  await expect(page.getByRole('button',{name:'Approve connection',exact:true})).toBeEnabled()
  await expect(page.getByRole('button',{name:'Cancel',exact:true})).toBeEnabled()
})


test('consent shows the reviewed account and requires another review after an account change',async({page})=>{
  let account={id:'first-user',email:'first.student@example.test'}
  const submissions=[]
  await page.route('**/api/mcp/consent?**',route=>route.fulfill({json:{name:'Research workspace',redirectUri:'https://example.org/callback',scopes:['read'],account}}))
  await page.route('**/api/mcp/consent',route=>{
    submissions.push(route.request().postDataJSON())
    return route.fulfill({status:409,json:{error:'account_changed',error_description:'Your signed-in account changed. Reload the connection to review the account before approving.'}})
  })
  await page.goto('/connect/remote?request=account-fixture')
  await expect(page.getByText(account.email,{exact:true})).toBeVisible()
  await expect(page.getByText('Make study changes',{exact:true})).toHaveCount(0)
  await expect(page.getByRole('link',{name:'Privacy notice',exact:true})).toHaveAttribute('href','/privacy')
  await expect(page.getByRole('link',{name:'Privacy notice',exact:true})).toHaveAttribute('target','_blank')
  await expect(page.getByRole('link',{name:'Terms',exact:true})).toHaveAttribute('href','/terms')
  await expect(page.getByRole('link',{name:'Support',exact:true})).toHaveAttribute('href','mailto:support@study.wicker.life')
  await page.getByRole('button',{name:'Approve connection',exact:true}).click()
  expect(submissions).toEqual([{request:'account-fixture',approved:true,accountId:'first-user'}])
  await expect(page.locator('main').getByRole('alert')).toContainText('account changed')
  await expect(page.getByRole('button',{name:'Approve connection',exact:true})).toHaveCount(0)
  await expect(page.getByText(account.email,{exact:true})).toHaveCount(0)
  account={id:'second-user',email:'another.student.with.a.long.email@student.maastrichtuniversity.nl'}
  await page.getByRole('button',{name:'Reload connection'}).click()
  await expect(page.getByText(account.email,{exact:true})).toBeVisible()
  await expect(page.getByRole('button',{name:'Approve connection',exact:true})).toBeEnabled()
  expect(submissions).toHaveLength(1)
  await page.setViewportSize({width:390,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.getByRole('button',{name:'Approve connection',exact:true}).click()
  expect(submissions[1].accountId).toBe('second-user')
})
