import { test, expect } from '@playwright/test'

test('signed-out remote connection has visible controls and preserves the approval return route', async ({ page }) => {
  await page.route('**/api/mcp/consent?**', route => route.fulfill({status:401,json:{error:'Sign in required'}}))
  await page.goto('/connect/remote?request=approval-fixture')
  const signIn=page.getByRole('link',{name:'Sign in to continue'})
  await expect(signIn).toBeVisible()
  await expect(signIn).toHaveAttribute('href','/sign-in?redirect_url=%2Fconnect%2Fremote%3Frequest%3Dapproval-fixture')
  const style=await signIn.evaluate(node=>({background:getComputedStyle(node).backgroundColor,height:node.getBoundingClientRect().height,padding:getComputedStyle(node.closest('section')).paddingTop}))
  expect(style.background).toBe('rgb(63, 81, 217)')
  expect(style.height).toBeGreaterThanOrEqual(44)
  expect(parseFloat(style.padding)).toBeGreaterThanOrEqual(24)
  await signIn.focus()
  expect(await signIn.evaluate(node=>getComputedStyle(node).outlineStyle)).toBe('solid')
  await page.setViewportSize({width:390,height:844})
  await expect(signIn).toBeInViewport()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})

test('remote connection distinguishes a failed list from an empty one and reviews exact permissions',async({page})=>{
  await page.route('**/api/mcp/connections',route=>route.fulfill({status:503,json:{error:'Connections are temporarily unavailable.'}}))
  await page.goto('/connect/remote')
  await expect(page.locator('main').getByRole('alert')).toContainText('temporarily unavailable')
  await expect(page.getByText('No services connected yet.')).toHaveCount(0)
  await page.unroute('**/api/mcp/connections')
  await page.route('**/api/mcp/connections',route=>route.fulfill({json:{connections:[{id:'fixture',name:'Research workspace',scopes:['read'],createdAt:'2026-09-08T00:00:00Z'}]}}))
  await page.reload()
  await expect(page.getByText('Research workspace',{exact:true})).toBeVisible()
  await expect(page.getByRole('button',{name:'Disconnect',exact:true})).toBeVisible()
  await page.route('**/api/mcp/consent?**',route=>route.fulfill({json:{name:'Research workspace',redirectUri:'https://example.org/callback',scopes:['read','write']}}))
  await page.goto('/connect/remote?request=approval-fixture')
  await expect(page.getByRole('heading',{name:'Connect Research workspace?'})).toBeVisible()
  await expect(page.getByText('Read your study data',{exact:true})).toBeVisible()
  await expect(page.getByText('Make study changes',{exact:true})).toBeVisible()
  await expect(page.getByRole('button',{name:'Approve connection',exact:true})).toBeEnabled()
  await expect(page.getByRole('button',{name:'Cancel',exact:true})).toBeEnabled()
})
