export type AttendanceStatus = 'unknown' | 'attended' | 'missed' | 'excused'
export type AttendanceRecord = { id: string; eventId: string; courseId: string | null; courseCode: string | null; courseName: string | null; title: string; activity: string; startsAt: string; endsAt: string | null; status: Exclude<AttendanceStatus, 'unknown'>; note: string; recordedAt: string }
export type AttendanceCourseSummary = { courseId: string | null; editorialCourseId: string | null; courseCode: string | null; courseName: string; scheduled: number; past: number; attended: number; missed: number; excused: number; unmarked: number; requiredScheduled: number; requiredPast: number; requiredAttended: number; requiredMissed: number; requiredExcused: number; requiredUnmarked: number; allowedMisses: number | null; allowedMissesRemaining: number | null; minimumAttendancePercent: number | null; rule: string | null; ruleSource: string | null; unknownRequirementSessions?: number; unmatchedRules?: Array<{text:string;activity:string;source:string}>; rate: number | null; requiredRate: number | null; atRisk: boolean }
export type AttendanceOverview = { summary: { scheduled: number; past: number; attended: number; missed: number; excused: number; unmarked: number; requiredMissed: number; requiredUnmarked: number; rate: number | null; atRiskCourses: number }; courses: AttendanceCourseSummary[] }
export declare function attendanceActivity(value: unknown): string
export declare function attendancePolicyForEvent(event: Record<string, unknown>, course: Record<string, any> | undefined): { required: boolean; text: string; activity: string; allowedMisses: number | null; minimumAttendancePercent: number | null; excusedPolicy: string; evidence: unknown[]; source: string } | null
export declare function normalizeAttendanceRecord(value: unknown, index?: number): AttendanceRecord | null
export declare function attendanceRecordForEvent(event: Record<string, any>, status: AttendanceStatus, note?: string, recordedAt?: Date | string): AttendanceRecord | null
export declare function upsertAttendanceRecord(records: unknown[], event: Record<string, any>, status: AttendanceStatus, note?: string, recordedAt?: Date | string): AttendanceRecord[]
export declare function attendanceOverview<T extends Record<string, any>>(events: T[], records: unknown[], courses: Record<string, any>[], options?: { now?: number }): AttendanceOverview & { events: Array<T & Record<string, any>> }
