import Link from 'next/link'
import { ArrowRightIcon, CalendarDaysIcon, FileTextIcon, ShieldCheckIcon } from 'lucide-react'
import { Bar, DATA, LABEL, ProtoHeader, RequirementRows } from './shared'

const evidence = [
  { claim: '92 ECTS earned', source: 'Transcript · version 4', checked: '2 Sep 2026', icon: FileTextIcon },
  { claim: 'P1 resits share the P2 exam window', source: 'Academic calendar · 2026–2027', checked: '1 Sep 2026', icon: CalendarDaysIcon },
  { claim: 'One required BCS3120 absence available', source: 'Course syllabus · attendance rule', checked: '31 Aug 2026', icon: ShieldCheckIcon },
] as const

export function EvidenceBrief() {
  return <main className="mx-auto flex min-h-dvh w-full max-w-[1240px] flex-col gap-8 p-5 pb-24 sm:p-8 sm:pb-24">
    <ProtoHeader title="Academic brief" description="A verified account of where the degree stands, what is inferred, and which source supports every planning decision." />
    <div className="grid items-start gap-6 xl:grid-cols-[300px_minmax(0,1fr)]">
      <aside className="overflow-hidden rounded-xl border bg-card"><header className="px-5 py-5"><span className={LABEL}>Recorded position</span><strong className={`font-heading mt-2 block text-4xl tracking-[-0.04em] ${DATA}`}>92 <small className="text-muted-foreground text-base font-medium">ECTS</small></strong><Bar value={51} className="mt-5" /><p className="text-muted-foreground mt-2 text-xs">51% of the bachelor recorded as passed</p></header><dl className="grid grid-cols-2 border-t"><div className="px-5 py-4"><dt className={LABEL}>GPA</dt><dd className={`mt-2 text-xl font-semibold ${DATA}`}>7.2</dd></div><div className="border-l px-5 py-4"><dt className={LABEL}>Attendance</dt><dd className={`mt-2 text-xl font-semibold ${DATA}`}>94%</dd></div></dl><div className="border-t px-5 py-4"><span className={LABEL}>Current interpretation</span><p className="mt-2 text-sm font-semibold leading-relaxed">On route, with one resit decision and 8 elective ECTS unresolved.</p></div><Link href="/app/planning?tab=planner" className="text-primary flex min-h-12 items-center justify-between border-t px-5 text-xs font-semibold">Test this interpretation<ArrowRightIcon className="size-3.5" /></Link></aside>
      <div className="flex flex-col gap-6"><section className="overflow-hidden rounded-xl border bg-card"><header className="flex items-baseline justify-between gap-4 px-5 py-4 sm:px-6"><div><span className={LABEL}>Evidence register</span><h2 className="font-heading mt-1 text-xl font-semibold">Claims used by the plan</h2></div><span className="text-primary text-xs font-semibold">3 verified</span></header><div className="border-t">{evidence.map((item) => <details key={item.claim} className="group border-t first:border-t-0"><summary className="grid min-h-[76px] cursor-pointer list-none grid-cols-[36px_minmax(0,1fr)_auto] items-center gap-3 px-5 py-3 marker:hidden hover:bg-muted/25 sm:px-6"><span className="bg-muted text-muted-foreground grid size-9 place-items-center rounded-[8px]"><item.icon className="size-4" /></span><span><strong className="block text-sm">{item.claim}</strong><span className="text-muted-foreground mt-1 block text-xs">{item.source}</span></span><span className={`text-muted-foreground text-[10px] ${DATA}`}>{item.checked}</span></summary><div className="bg-muted/30 border-t px-5 py-4 text-xs leading-relaxed sm:px-6">This fact is stored separately from your private scenario. Replacing its source creates a new document version and asks you to review any changed claim.</div></details>)}</div></section>
      <section className="overflow-hidden rounded-xl border bg-card"><header className="px-5 py-4 sm:px-6"><span className={LABEL}>Requirement ledger</span><h2 className="font-heading mt-1 text-xl font-semibold">What remains binding</h2></header><div className="border-t"><RequirementRows /></div></section></div>
    </div>
    <section className="overflow-hidden rounded-xl border bg-card"><header className="grid gap-4 px-5 py-4 sm:grid-cols-[minmax(0,1fr)_auto] sm:px-6"><div><span className={LABEL}>Next examination window</span><h2 className="font-heading mt-1 text-xl font-semibold">Period 2 exams + Period 1 resits</h2><p className="text-muted-foreground mt-1 text-xs">Combined by matching dates in the 2026–2027 academic calendar</p></div><strong className={`self-center text-lg ${DATA}`}>14–18 Dec</strong></header><div className="grid border-t md:grid-cols-2"><div className="px-5 py-4 sm:px-6"><span className={LABEL}>First sittings</span><strong className="mt-2 block text-sm">Period 2 courses</strong></div><div className="border-t px-5 py-4 md:border-t-0 md:border-l sm:px-6"><span className={LABEL}>Resits</span><strong className="mt-2 block text-sm">Period 1 courses</strong></div></div></section>
  </main>
}
