import Link from 'next/link'
import { ArrowRightIcon, CheckCircle2Icon } from 'lucide-react'
import { Bar, DATA, decisions, LABEL, ProtoHeader, RequirementRows } from './shared'

export function StatusDecisions() {
  return <main className="mx-auto flex min-h-dvh w-full max-w-[1240px] flex-col gap-8 p-5 pb-24 sm:p-8 sm:pb-24">
    <ProtoHeader title="Your academic position" description="The recorded degree status, decisions that can change it, and the requirements your current plan must still clear." />
    <section className="overflow-hidden rounded-xl border bg-card">
      <div className="grid lg:grid-cols-[minmax(0,1.5fr)_repeat(3,minmax(130px,0.5fr))]">
        <div className="px-5 py-5 sm:px-6"><span className={LABEL}>Degree completion</span><div className="mt-2 flex items-end justify-between gap-6"><strong className={`font-heading text-4xl tracking-[-0.04em] ${DATA}`}>92 <small className="text-muted-foreground text-base font-medium">/ 180 ECTS</small></strong><span className="text-primary text-xs font-semibold">51% complete</span></div><Bar value={51} className="mt-4" /><div className="text-muted-foreground mt-2 flex justify-between text-xs"><span>92 earned</span><span>32 planned this year</span></div></div>
        {[['Passed', '18', 'courses'], ['Attendance', '94%', '1 allowed miss left'], ['Expected', '7.4', 'saved scenario']].map(([label, value, note]) => <div key={label} className="border-t px-5 py-5 lg:border-t-0 lg:border-l"><span className={LABEL}>{label}</span><strong className={`mt-3 block text-2xl ${DATA}`}>{value}</strong><span className="text-muted-foreground mt-1 block text-xs">{note}</span></div>)}
      </div>
    </section>
    <div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1.15fr)_minmax(340px,0.85fr)]">
      <section className="overflow-hidden rounded-xl border bg-card"><header className="flex items-baseline justify-between gap-4 px-5 py-4 sm:px-6"><div><span className={LABEL}>Needs a decision</span><h2 className="font-heading mt-1 text-xl font-semibold">Three things can change the route</h2></div><span className={`text-muted-foreground text-xs ${DATA}`}>This term</span></header><div className="border-t">{decisions.map((item) => <Link key={item.label} href={item.href} className="group grid min-h-[78px] grid-cols-[36px_minmax(0,1fr)_auto] items-center gap-3 border-t px-5 py-3 first:border-t-0 hover:bg-muted/25 sm:px-6"><span className={`grid size-9 place-items-center rounded-[8px] ${item.tone === 'attention' ? 'bg-primary/10 text-primary' : 'bg-muted text-muted-foreground'}`}><item.icon className="size-4" /></span><span><strong className="block text-sm">{item.label}</strong><span className="text-muted-foreground mt-1 block text-xs">{item.detail}</span></span><span className="flex items-center gap-2 text-xs font-semibold"><span className={`text-muted-foreground ${DATA}`}>{item.date}</span><ArrowRightIcon className="size-3.5 transition-transform group-hover:translate-x-0.5" /></span></Link>)}</div></section>
      <section className="overflow-hidden rounded-xl border bg-card"><header className="px-5 py-4 sm:px-6"><span className={LABEL}>Requirements</span><h2 className="font-heading mt-1 text-xl font-semibold">What the route must satisfy</h2></header><div className="border-t"><RequirementRows /></div><Link href="/app/planning?tab=overview" className="text-primary flex min-h-12 items-center justify-between border-t px-5 text-xs font-semibold sm:px-6">Manage requirements<ArrowRightIcon className="size-3.5" /></Link></section>
    </div>
    <section className="overflow-hidden rounded-xl border bg-card"><header className="flex items-center justify-between px-5 py-4 sm:px-6"><div><span className={LABEL}>Study years</span><h2 className="font-heading mt-1 text-xl font-semibold">Progress across the bachelor</h2></div><span className="text-primary inline-flex items-center gap-1.5 text-xs font-semibold"><CheckCircle2Icon className="size-4" />Year 1 cleared</span></header><div className="grid border-t md:grid-cols-3">{[['Year 1',60,60,'Complete'],['Year 2',32,60,'28 ECTS open'],['Year 3',0,60,'32 ECTS planned']].map(([year, value, total, note], index) => <div key={String(year)} className={`px-5 py-4 sm:px-6 ${index ? 'border-t md:border-t-0 md:border-l' : ''}`}><div className="flex justify-between"><strong className="text-sm">{year}</strong><span className={`text-muted-foreground text-xs ${DATA}`}>{value}/{total}</span></div><Bar value={Number(value) / Number(total) * 100} className="mt-4" /><p className="text-muted-foreground mt-2 text-xs">{note}</p></div>)}</div></section>
  </main>
}
