import type { Metadata } from 'next'
import { ContactLink } from '@/components/site/contact-link'
import { operatorName } from '@/lib/site-content'

export const metadata: Metadata = { title: 'Terms of service' }

export default function TermsPage() {
  return (
    <main id="main-content" className="legal-page">
      <header className="legal-hero"><div><h1>Terms of service</h1><p>The rules for accessing and using Wicker Study.</p></div><dl><div><dt>Effective</dt><dd>30 August 2026</dd></div><div><dt>Operator</dt><dd>{operatorName}</dd></div><div><dt>Contact</dt><dd><ContactLink kind="legal" /></dd></div></dl></header>
      <div className="legal-layout">
        <nav aria-label="Terms sections"><a href="#service">Service</a><a href="#accounts">Accounts</a><a href="#academic">Academic use</a><a href="#content">Content</a><a href="#ai">AI features</a><a href="#acceptable">Acceptable use</a><a href="#availability">Availability</a><a href="#ending">Ending use</a><a href="#contact">Contact</a></nav>
        <article>
          <section id="service"><h2>1. The service and operator</h2><p>These terms are between you and {operatorName}, an individual operating the service under the name Wicker Study. Wicker Study provides a private workspace for accessing maintained course material, recording study progress, practising questions, reviewing flashcards and mistakes, running mock sessions, and using limited source-grounded AI assistance.</p></section>
          <section id="accounts"><h2>2. Accounts and access</h2><p>You are responsible for the security of your sign-in method and for activity under your account. Provide accurate account information and notify us promptly if you believe access has been compromised. The service is intended for university-level learners able to enter into these terms.</p></section>
          <section id="academic"><h2>3. Academic use</h2><p>The service supports study but does not replace lectures, official module documents, instructors, or examination rules. You remain responsible for checking material and complying with your institution’s academic-integrity requirements. No grade or examination outcome is guaranteed.</p></section>
          <section id="content"><h2>4. Course, personal, and contributed content</h2><p>Course materials and the platform interface remain protected by their applicable intellectual-property rights. You may use them for personal study within the service and may not redistribute, scrape, resell, or republish them without permission. You retain rights in personal notes and answers you create.</p><p>When you attach material to a course request, you confirm that you may lawfully access it and share it privately for this processing purpose. You permit Wicker Study to store, inspect, extract, and use the submission to evaluate and prepare your request. Private submission alone does not permit shared publication or redistribution.</p><p>If you separately select the shared-course contribution option, you confirm the stated rights basis and grant {operatorName} a non-exclusive, worldwide, royalty-free licence to store, extract, index, analyse, adapt, combine, and use that contribution to create, maintain, and publish educational derivatives through Wicker Study. You keep ownership of your own material. The option does not claim ownership of third-party material or expand rights you do not have, and source originals are not automatically made public. Administrators must review rights, evidence, and generated drafts before publication. You can withdraw a contribution from future processing from the request or by contacting <ContactLink kind="privacy" />; withdrawal does not undo prior lawful processing or require removal of an already-published derivative that contains no personal data and remains lawfully licensed, subject always to rights that cannot be waived.</p><p>Do not submit another person’s private data, leaked or confidential assessment material, or content obtained by bypassing access controls. Remove unnecessary names, student numbers, comments, and other personal information before uploading.</p></section>
          <section id="ai"><h2>5. AI-assisted features</h2><p>AI is used for retrieval-grounded tutor chat, further exercises requested by the user, academic-plan extraction, and source-grounded preparation of course content under administrator review. Editorial generation is not automatic: sources are rights-reviewed, generation is deliberately queued, drafts retain evidence links, and publication requires approval. Responses and generated materials can still be incomplete or incorrect and should be verified against cited course sources and official assessment rules. Usage limits protect service capacity and may be adjusted. Attempts to bypass limits or use AI endpoints outside their intended study purpose are prohibited.</p></section>
          <section id="acceptable"><h2>6. Acceptable use</h2><p>Do not interfere with the service, attempt unauthorised access, upload malicious material, abuse other users, automate excessive requests, circumvent security or usage controls, or use the service in a way that violates law or third-party rights.</p></section>
          <section id="availability"><h2>7. Availability and changes</h2><p>We aim to keep the service dependable, but access may be interrupted for maintenance, security, provider outages, or changes to course availability. Features and course content may change as the maintained curriculum evolves.</p></section>
          <section id="warranty"><h2>8. Responsibility</h2><p>The service is provided on an as-available basis. To the maximum extent permitted by applicable law, Wicker Study is not responsible for indirect loss, lost academic opportunity, or decisions made solely from generated output. Nothing in these terms excludes rights or liability that cannot legally be excluded.</p></section>
          <section id="ending"><h2>9. Ending use</h2><p>You may stop using the service at any time and can export your personal data or permanently delete your account from Settings. Access may be suspended where reasonably necessary to protect the service, other users, or legal compliance.</p></section>
          <section id="contact"><h2>10. Contact and changes</h2><p>Questions about these terms and formal notices can be sent to <ContactLink kind="legal" />. Account and product help can be sent to <ContactLink kind="support" />. Material revisions will be dated on this page. Continued use after revised terms take effect indicates acceptance where permitted by law.</p></section>
        </article>
      </div>
    </main>
  )
}
